import {
  AUTOMATION_CONFIG_TRIGGER_TYPES,
  AUTOMATION_DISPATCH_ACTION_STATUSES,
  AUTOMATION_DISPATCH_ACTION_STATUS,
  AUTOMATION_TERMINATE_ACTION_STATUSES,
  AUTOMATION_TERMINATE_ACTION_STATUS,
  AUTOMATION_TRIGGER_EVENT_STATUSES,
  AUTOMATION_TRIGGER_EVENT_STATUS,
  AUTOMATION_TRIGGER_EVENT_MATCH_STATUSES,
  AUTOMATION_TRIGGER_EVENT_MATCH_STATUS,
  AUTOMATION_RUNNER_TYPES,
  AUTOMATION_MODEL_CLASSES,
  AUTOMATION_RUN_TRIGGER_TYPES,
  AUTOMATION_RUN_OUTCOME_SUMMARY_MAX_LENGTH,
  type AutomationTriggerEventStatus,
  type AutomationDispatchActionStatus,
  type AutomationTerminateActionStatus,
  type AutomationConfigTriggerType,
  type AutomationRunTriggerType,
  type AutomationRunnerType,
  type AutomationModelClass,
} from "../packages/shared/src/automations.js";
import {
  CUSTOM_MCP_SERVER_STATUSES,
  CUSTOM_MCP_SERVER_STATUS,
  PROVIDER_METRIC_NAMES,
  PROVIDER_METRIC_OUTCOMES,
  type CustomMcpServerStatus,
} from "../packages/shared/src/domain.js";
import {
  INTEGRATION_ERROR_CATEGORIES,
  INTEGRATION_ERROR_CODES,
  KEPPO_ERROR_CODE,
  KEPPO_ERROR_CODE_LITERALS,
  type IntegrationErrorCategory,
  type IntegrationErrorCode,
  type KeppoErrorCodeLiteral,
} from "../packages/shared/src/execution-errors.js";

export {
  ACTION_RISK_LEVELS,
  ACTION_STATUS,
  ACTION_STATUSES,
  API_DEDUPE_SCOPES,
  API_DEDUPE_STATUSES,
  API_DEDUPE_STATUS,
  OAUTH_DEDUPE_RESOLUTION_STATUSES,
  OAUTH_DEDUPE_RESOLUTION_STATUS,
  APPROVAL_DECIDER_TYPES,
  APPROVAL_DECIDER_TYPE,
  APPROVAL_DECISIONS,
  APPROVAL_DECISION,
  CLIENT_TYPE,
  CLIENT_TYPES,
  DEAD_LETTER_SOURCES,
  DEAD_LETTER_SOURCE,
  DEAD_LETTER_STATUSES,
  DEAD_LETTER_STATUS,
  DECISION_OUTCOMES,
  DECISION_OUTCOME,
  CREDENTIAL_TYPES,
  CREDENTIAL_TYPE,
  CRON_HEALTH_STATUSES,
  CRON_HEALTH_STATUS,
  CUSTOM_MCP_SERVER_STATUSES,
  CUSTOM_MCP_SERVER_STATUS,
  DEFAULT_ACTION_BEHAVIOR,
  DEFAULT_ACTION_BEHAVIORS,
  INTEGRATION_STATUSES,
  INTEGRATION_STATUS,
  INVITE_CODE_REDEMPTION_STATUSES,
  INVITE_CODE_REDEMPTION_STATUS,
  INVITE_STATUSES,
  INVITE_STATUS,
  NOTIFICATION_DELIVERY_STATUSES,
  NOTIFICATION_DELIVERY_STATUS,
  POLICY_DECISION_RESULTS,
  POLICY_MODE,
  POLICY_MODES,
  PROVIDER_DEPRECATION_STATUSES,
  PROVIDER_DEPRECATION_STATUS,
  PROVIDER_CATALOG_CONFIGURATION_STATUSES,
  PROVIDER_CATALOG_CONFIGURATION_STATUS,
  PROVIDER_METRIC_NAME,
  PROVIDER_METRIC_OUTCOME,
  PROVIDER_METRIC_ALERT_SEVERITIES,
  PROVIDER_METRIC_ALERT_SEVERITY,
  OUTPUT_SENSITIVITIES,
  OUTPUT_SENSITIVITY,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_CHANNEL,
  NOTIFICATION_ENDPOINT_TYPES,
  NOTIFICATION_ENDPOINT_TYPE,
  RULE_EFFECTS,
  RULE_EFFECT,
  RUN_STATUSES,
  RUN_STATUS,
  SUBSCRIPTION_STATUSES,
  SUBSCRIPTION_STATUS,
  SUBSCRIPTION_TIERS,
  SUBSCRIPTION_TIER,
  E2E_ACTION_TRIGGER_STATUSES,
  E2E_ACTION_TRIGGER_STATUS,
  CUSTOM_INTEGRATION_AUTH_METHODS,
  CUSTOM_INTEGRATION_AUTH_METHOD,
  AUTOMATION_RUN_ARCHIVED_LOG_ENCODINGS,
  AUTOMATION_RUN_ARCHIVED_LOG_ENCODING,
  ABUSE_FLAG_STATUSES,
  ABUSE_FLAG_STATUS,
  ABUSE_FLAG_SEVERITIES,
  ABUSE_FLAG_SEVERITY,
  ABUSE_FLAG_REVIEW_STATUSES,
  ABUSE_FLAG_REVIEW_STATUS,
  AUDIT_ACTOR_TYPES,
  AUDIT_ACTOR_TYPE,
  AUDIT_ERROR_EVENT_TYPES,
  AUDIT_ERROR_EVENT_TYPE_SET,
  AUDIT_EVENT_TYPES,
  SECURITY_AUDIT_EVENT_TYPES,
  TOOL_CAPABILITIES,
  TOOL_CAPABILITY,
  TOOL_CALL_RESULT_STATUSES,
  TOOL_CALL_RESULT_STATUS,
  TOOL_CALL_STATUSES,
  TOOL_CALL_STATUS,
  USER_ROLES,
  USER_ROLE,
  WORKSPACE_STATUSES,
  WORKSPACE_STATUS,
  AI_CREDIT_PURCHASE_STATUSES,
  AI_CREDIT_PURCHASE_STATUS,
  AUTOMATION_RUN_TOPUP_PURCHASE_STATUSES,
  AUTOMATION_RUN_TOPUP_PURCHASE_STATUS,
  type ActionRiskLevel,
  type ActionStatus,
  type ApiDedupeScope,
  type ApiDedupeStatus,
  type OAuthDedupeResolutionStatus,
  type ApprovalDeciderType,
  type ApprovalDecision,
  type CredentialType,
  type CronHealthStatus,
  type CustomMcpServerStatus,
  type ClientType,
  type DeadLetterSource,
  type DeadLetterStatus,
  type DecisionOutcome,
  type DefaultActionBehavior,
  type IntegrationStatus,
  type InviteCodeRedemptionStatus,
  type InviteStatus,
  type NotificationDeliveryStatus,
  type OutputSensitivity,
  type PolicyDecisionResult,
  type PolicyMode,
  type ProviderCatalogConfigurationStatus,
  type ProviderDeprecationStatus,
  type ProviderMetricAlertSeverity,
  type RuleEffect,
  type RunStatus,
  type SubscriptionStatus,
  type SubscriptionTier,
  type ToolCapability,
  type ToolCallResultStatus,
  type ToolCallStatus,
  type ActionPollStatus,
  type NotificationChannelValue,
  type NotificationEndpointTypeValue,
  type AutomationRunArchivedLogEncoding,
  type E2eActionTriggerStatus,
  type CustomIntegrationAuthMethod,
  type AbuseFlagStatus,
  type AbuseFlagSeverity,
  type AbuseFlagReviewStatus,
  type AuditActorType,
  type AuditEventType,
  type UserRole,
  type WorkspaceStatus,
  type AiCreditPurchaseStatus,
  type AutomationRunTopupPurchaseStatus,
  QUEUE_ENQUEUE_ERROR_CODES,
  QUEUE_ENQUEUE_ERROR_CODE,
  type QueueEnqueueErrorCode,
  assertNever,
  ACTION_POLL_STATUSES,
  ACTION_POLL_STATUS,
} from "../packages/shared/src/domain.js";

export { PROVIDER_METRIC_NAMES, PROVIDER_METRIC_OUTCOMES };
export const DEAD_LETTER_ERROR_CODES = KEPPO_ERROR_CODE_LITERALS;
export type DeadLetterErrorCode = KeppoErrorCodeLiteral;
export const DEAD_LETTER_ERROR_CODE = KEPPO_ERROR_CODE;
export {
  INTEGRATION_ERROR_CATEGORIES,
  INTEGRATION_ERROR_CODES,
  type IntegrationErrorCategory,
  type IntegrationErrorCode,
};
export {
  NOTIFICATION_EVENT_ID,
  type NotificationEventId,
} from "../packages/shared/src/notifications.js";

export {
  AUTOMATION_PROVIDER_TRIGGER_DELIVERY_MODES,
  AUTOMATION_PROVIDER_TRIGGER_DELIVERY_MODE,
  AUTOMATION_PROVIDER_TRIGGER_SUBSCRIPTION_STATUSES,
  AUTOMATION_PROVIDER_TRIGGER_SUBSCRIPTION_STATUS,
  AUTOMATION_PROVIDER_TRIGGER_MIGRATION_STATUSES,
  AUTOMATION_PROVIDER_TRIGGER_MIGRATION_STATUS,
  AUTOMATION_PROVIDER_TRIGGER_SCHEMA_VERSION,
  AUTOMATION_DISPATCH_ACTION_STATUSES,
  AUTOMATION_DISPATCH_ACTION_STATUS,
  AI_KEY_CREDENTIAL_KINDS,
  AI_KEY_CREDENTIAL_KIND,
  AUTOMATION_RUN_LOG_LEVELS,
  AUTOMATION_RUN_EVENT_TYPES,
  AUTOMATION_RUN_EVENT_TYPE,
  AUTOMATION_RUN_OUTCOME_SOURCES,
  AUTOMATION_RUN_OUTCOME_SOURCE,
  AUTOMATION_RUN_OUTCOME_SUMMARY_MAX_LENGTH,
  AUTOMATION_TRIGGER_EVENT_STATUSES,
  AUTOMATION_TRIGGER_EVENT_STATUS,
  AUTOMATION_TRIGGER_EVENT_MATCH_STATUSES,
  AUTOMATION_TRIGGER_EVENT_MATCH_STATUS,
  AUTOMATION_TERMINATE_ACTION_STATUSES,
  AUTOMATION_TERMINATE_ACTION_STATUS,
  isAutomationRunFailureStatus,
  isAutomationRunStatus,
  isAutomationRunTerminalStatus,
  AUTOMATION_RUN_STATUSES,
  AUTOMATION_RUN_STATUS,
  AUTOMATION_STATUSES,
  AUTOMATION_STATUS,
  AI_KEY_MODE,
  AI_KEY_MODES,
  AUTOMATION_MODEL_CLASSES,
  AUTOMATION_MODEL_CLASS,
  AI_MODEL_PROVIDERS,
  NETWORK_ACCESS_MODES,
  type AutomationRunLogLevel,
  type AutomationRunEventType,
  type AutomationRunFailureStatus,
  type AutomationRunOutcomeSource,
  type AutomationRunStatus,
  type AutomationDispatchActionStatus,
  type AutomationTerminateActionStatus,
  type AutomationTriggerEventStatus,
  type AutomationProviderTriggerDeliveryMode,
  type AutomationProviderTriggerSubscriptionStatus,
  type AutomationProviderTriggerMigrationStatus,
  type AutomationProviderTriggerDeliveryMetadata,
  type AutomationProviderTriggerSubscriptionState,
  type AutomationProviderTrigger,
  type AutomationProviderTriggerMigrationState,
  type AutomationStatus,
  type AutomationModelClass,
  type AiKeyCredentialKind,
  type AiKeyMode,
  type AiModelProvider,
  type NetworkAccessMode,
} from "../packages/shared/src/automations.js";

export const CONFIG_TRIGGER_TYPES = AUTOMATION_CONFIG_TRIGGER_TYPES;
export type ConfigTriggerType = AutomationConfigTriggerType;
export const MODEL_CLASSES = AUTOMATION_MODEL_CLASSES;
export type ModelClass = AutomationModelClass;

export const RUN_TRIGGER_TYPES = AUTOMATION_RUN_TRIGGER_TYPES;
export type RunTriggerType = AutomationRunTriggerType;
export const RUN_TRIGGER_TYPE = {
  schedule: RUN_TRIGGER_TYPES[0],
  event: RUN_TRIGGER_TYPES[1],
  manual: RUN_TRIGGER_TYPES[2],
} as const satisfies Record<string, RunTriggerType>;

export const RUNNER_TYPES = AUTOMATION_RUNNER_TYPES;
export type RunnerType = AutomationRunnerType;

export type ProviderMetricName = (typeof PROVIDER_METRIC_NAMES)[number];
export type ProviderMetricOutcome = (typeof PROVIDER_METRIC_OUTCOMES)[number];
