/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as HealthRouteImport } from "./routes/health";
import { Route as WebhooksStripeBillingRouteImport } from "./routes/webhooks/stripe-billing";
import { Route as WebhooksProviderRouteImport } from "./routes/webhooks/$provider";
import { Route as McpWorkspaceIdRouteImport } from "./routes/mcp/$workspaceId";
import { Route as BillingUsageRouteImport } from "./routes/billing/usage";
import { Route as BillingPortalRouteImport } from "./routes/billing/portal";
import { Route as BillingExtraUsageRouteImport } from "./routes/billing/extra-usage";
import { Route as BillingCheckoutRouteImport } from "./routes/billing/checkout";
import { Route as ApiSearchRouteImport } from "./routes/api/search";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as InternalQueueDispatchApprovedActionRouteImport } from "./routes/internal/queue/dispatch-approved-action";
import { Route as InternalNotificationsDeliverRouteImport } from "./routes/internal/notifications/deliver";
import { Route as InternalCronMaintenanceRouteImport } from "./routes/internal/cron/maintenance";
import { Route as InternalAutomationsTerminateRouteImport } from "./routes/internal/automations/terminate";
import { Route as InternalAutomationsLogRouteImport } from "./routes/internal/automations/log";
import { Route as InternalAutomationsDispatchRouteImport } from "./routes/internal/automations/dispatch";
import { Route as InternalAutomationsCompleteRouteImport } from "./routes/internal/automations/complete";
import { Route as BillingCreditsCheckoutRouteImport } from "./routes/billing/credits/checkout";
import { Route as ApiMcpTestRouteImport } from "./routes/api/mcp/test";
import { Route as ApiInvitesCreateRouteImport } from "./routes/api/invites/create";
import { Route as ApiInvitesAcceptRouteImport } from "./routes/api/invites/accept";
import { Route as ApiHealthFlagsRouteImport } from "./routes/api/health/flags";
import { Route as ApiHealthDlqRouteImport } from "./routes/api/health/dlq";
import { Route as ApiHealthDeepRouteImport } from "./routes/api/health/deep";
import { Route as ApiHealthAuditErrorsRouteImport } from "./routes/api/health/audit-errors";
import { Route as ApiBillingUsageRouteImport } from "./routes/api/billing/usage";
import { Route as ApiBillingPortalRouteImport } from "./routes/api/billing/portal";
import { Route as ApiBillingExtraUsageRouteImport } from "./routes/api/billing/extra-usage";
import { Route as ApiBillingCheckoutRouteImport } from "./routes/api/billing/checkout";
import { Route as ApiAutomationsGenerateQuestionsRouteImport } from "./routes/api/automations/generate-questions";
import { Route as ApiAutomationsGeneratePromptRouteImport } from "./routes/api/automations/generate-prompt";
import { Route as OauthIntegrationsProviderCallbackRouteImport } from "./routes/oauth/integrations/$provider/callback";
import { Route as ApiNotificationsPushSubscribeRouteImport } from "./routes/api/notifications/push/subscribe";
import { Route as ApiBillingCreditsCheckoutRouteImport } from "./routes/api/billing/credits/checkout";
import { Route as ApiBillingAutomationRunsCheckoutRouteImport } from "./routes/api/billing/automation-runs/checkout";
import { Route as ApiOauthIntegrationsProviderConnectRouteImport } from "./routes/api/oauth/integrations/$provider/connect";
import { Route as ApiHealthDlqIdReplayRouteImport } from "./routes/api/health/dlq/$id/replay";
import { Route as ApiHealthDlqIdAbandonRouteImport } from "./routes/api/health/dlq/$id/abandon";

const HealthRoute = HealthRouteImport.update({
  id: "/health",
  path: "/health",
  getParentRoute: () => rootRouteImport,
} as any);
const WebhooksStripeBillingRoute = WebhooksStripeBillingRouteImport.update({
  id: "/webhooks/stripe-billing",
  path: "/webhooks/stripe-billing",
  getParentRoute: () => rootRouteImport,
} as any);
const WebhooksProviderRoute = WebhooksProviderRouteImport.update({
  id: "/webhooks/$provider",
  path: "/webhooks/$provider",
  getParentRoute: () => rootRouteImport,
} as any);
const McpWorkspaceIdRoute = McpWorkspaceIdRouteImport.update({
  id: "/mcp/$workspaceId",
  path: "/mcp/$workspaceId",
  getParentRoute: () => rootRouteImport,
} as any);
const BillingUsageRoute = BillingUsageRouteImport.update({
  id: "/billing/usage",
  path: "/billing/usage",
  getParentRoute: () => rootRouteImport,
} as any);
const BillingPortalRoute = BillingPortalRouteImport.update({
  id: "/billing/portal",
  path: "/billing/portal",
  getParentRoute: () => rootRouteImport,
} as any);
const BillingExtraUsageRoute = BillingExtraUsageRouteImport.update({
  id: "/billing/extra-usage",
  path: "/billing/extra-usage",
  getParentRoute: () => rootRouteImport,
} as any);
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: "/billing/checkout",
  path: "/billing/checkout",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const InternalQueueDispatchApprovedActionRoute =
  InternalQueueDispatchApprovedActionRouteImport.update({
    id: "/internal/queue/dispatch-approved-action",
    path: "/internal/queue/dispatch-approved-action",
    getParentRoute: () => rootRouteImport,
  } as any);
const InternalNotificationsDeliverRoute =
  InternalNotificationsDeliverRouteImport.update({
    id: "/internal/notifications/deliver",
    path: "/internal/notifications/deliver",
    getParentRoute: () => rootRouteImport,
  } as any);
const InternalCronMaintenanceRoute = InternalCronMaintenanceRouteImport.update({
  id: "/internal/cron/maintenance",
  path: "/internal/cron/maintenance",
  getParentRoute: () => rootRouteImport,
} as any);
const InternalAutomationsTerminateRoute =
  InternalAutomationsTerminateRouteImport.update({
    id: "/internal/automations/terminate",
    path: "/internal/automations/terminate",
    getParentRoute: () => rootRouteImport,
  } as any);
const InternalAutomationsLogRoute = InternalAutomationsLogRouteImport.update({
  id: "/internal/automations/log",
  path: "/internal/automations/log",
  getParentRoute: () => rootRouteImport,
} as any);
const InternalAutomationsDispatchRoute =
  InternalAutomationsDispatchRouteImport.update({
    id: "/internal/automations/dispatch",
    path: "/internal/automations/dispatch",
    getParentRoute: () => rootRouteImport,
  } as any);
const InternalAutomationsCompleteRoute =
  InternalAutomationsCompleteRouteImport.update({
    id: "/internal/automations/complete",
    path: "/internal/automations/complete",
    getParentRoute: () => rootRouteImport,
  } as any);
const BillingCreditsCheckoutRoute = BillingCreditsCheckoutRouteImport.update({
  id: "/billing/credits/checkout",
  path: "/billing/credits/checkout",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiMcpTestRoute = ApiMcpTestRouteImport.update({
  id: "/api/mcp/test",
  path: "/api/mcp/test",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiInvitesCreateRoute = ApiInvitesCreateRouteImport.update({
  id: "/api/invites/create",
  path: "/api/invites/create",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiInvitesAcceptRoute = ApiInvitesAcceptRouteImport.update({
  id: "/api/invites/accept",
  path: "/api/invites/accept",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthFlagsRoute = ApiHealthFlagsRouteImport.update({
  id: "/flags",
  path: "/flags",
  getParentRoute: () => ApiHealthRoute,
} as any);
const ApiHealthDlqRoute = ApiHealthDlqRouteImport.update({
  id: "/dlq",
  path: "/dlq",
  getParentRoute: () => ApiHealthRoute,
} as any);
const ApiHealthDeepRoute = ApiHealthDeepRouteImport.update({
  id: "/deep",
  path: "/deep",
  getParentRoute: () => ApiHealthRoute,
} as any);
const ApiHealthAuditErrorsRoute = ApiHealthAuditErrorsRouteImport.update({
  id: "/audit-errors",
  path: "/audit-errors",
  getParentRoute: () => ApiHealthRoute,
} as any);
const ApiBillingUsageRoute = ApiBillingUsageRouteImport.update({
  id: "/api/billing/usage",
  path: "/api/billing/usage",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: "/api/billing/portal",
  path: "/api/billing/portal",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingExtraUsageRoute = ApiBillingExtraUsageRouteImport.update({
  id: "/api/billing/extra-usage",
  path: "/api/billing/extra-usage",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: "/api/billing/checkout",
  path: "/api/billing/checkout",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAutomationsGenerateQuestionsRoute =
  ApiAutomationsGenerateQuestionsRouteImport.update({
    id: "/api/automations/generate-questions",
    path: "/api/automations/generate-questions",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiAutomationsGeneratePromptRoute =
  ApiAutomationsGeneratePromptRouteImport.update({
    id: "/api/automations/generate-prompt",
    path: "/api/automations/generate-prompt",
    getParentRoute: () => rootRouteImport,
  } as any);
const OauthIntegrationsProviderCallbackRoute =
  OauthIntegrationsProviderCallbackRouteImport.update({
    id: "/oauth/integrations/$provider/callback",
    path: "/oauth/integrations/$provider/callback",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiNotificationsPushSubscribeRoute =
  ApiNotificationsPushSubscribeRouteImport.update({
    id: "/api/notifications/push/subscribe",
    path: "/api/notifications/push/subscribe",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiBillingCreditsCheckoutRoute =
  ApiBillingCreditsCheckoutRouteImport.update({
    id: "/api/billing/credits/checkout",
    path: "/api/billing/credits/checkout",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiBillingAutomationRunsCheckoutRoute =
  ApiBillingAutomationRunsCheckoutRouteImport.update({
    id: "/api/billing/automation-runs/checkout",
    path: "/api/billing/automation-runs/checkout",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiOauthIntegrationsProviderConnectRoute =
  ApiOauthIntegrationsProviderConnectRouteImport.update({
    id: "/api/oauth/integrations/$provider/connect",
    path: "/api/oauth/integrations/$provider/connect",
    getParentRoute: () => rootRouteImport,
  } as any);
const ApiHealthDlqIdReplayRoute = ApiHealthDlqIdReplayRouteImport.update({
  id: "/$id/replay",
  path: "/$id/replay",
  getParentRoute: () => ApiHealthDlqRoute,
} as any);
const ApiHealthDlqIdAbandonRoute = ApiHealthDlqIdAbandonRouteImport.update({
  id: "/$id/abandon",
  path: "/$id/abandon",
  getParentRoute: () => ApiHealthDlqRoute,
} as any);

export interface FileRoutesByFullPath {
  "/health": typeof HealthRoute;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/search": typeof ApiSearchRoute;
  "/billing/checkout": typeof BillingCheckoutRoute;
  "/billing/extra-usage": typeof BillingExtraUsageRoute;
  "/billing/portal": typeof BillingPortalRoute;
  "/billing/usage": typeof BillingUsageRoute;
  "/mcp/$workspaceId": typeof McpWorkspaceIdRoute;
  "/webhooks/$provider": typeof WebhooksProviderRoute;
  "/webhooks/stripe-billing": typeof WebhooksStripeBillingRoute;
  "/api/automations/generate-prompt": typeof ApiAutomationsGeneratePromptRoute;
  "/api/automations/generate-questions": typeof ApiAutomationsGenerateQuestionsRoute;
  "/api/billing/checkout": typeof ApiBillingCheckoutRoute;
  "/api/billing/extra-usage": typeof ApiBillingExtraUsageRoute;
  "/api/billing/portal": typeof ApiBillingPortalRoute;
  "/api/billing/usage": typeof ApiBillingUsageRoute;
  "/api/health/audit-errors": typeof ApiHealthAuditErrorsRoute;
  "/api/health/deep": typeof ApiHealthDeepRoute;
  "/api/health/dlq": typeof ApiHealthDlqRouteWithChildren;
  "/api/health/flags": typeof ApiHealthFlagsRoute;
  "/api/invites/accept": typeof ApiInvitesAcceptRoute;
  "/api/invites/create": typeof ApiInvitesCreateRoute;
  "/api/mcp/test": typeof ApiMcpTestRoute;
  "/billing/credits/checkout": typeof BillingCreditsCheckoutRoute;
  "/internal/automations/complete": typeof InternalAutomationsCompleteRoute;
  "/internal/automations/dispatch": typeof InternalAutomationsDispatchRoute;
  "/internal/automations/log": typeof InternalAutomationsLogRoute;
  "/internal/automations/terminate": typeof InternalAutomationsTerminateRoute;
  "/internal/cron/maintenance": typeof InternalCronMaintenanceRoute;
  "/internal/notifications/deliver": typeof InternalNotificationsDeliverRoute;
  "/internal/queue/dispatch-approved-action": typeof InternalQueueDispatchApprovedActionRoute;
  "/api/billing/automation-runs/checkout": typeof ApiBillingAutomationRunsCheckoutRoute;
  "/api/billing/credits/checkout": typeof ApiBillingCreditsCheckoutRoute;
  "/api/notifications/push/subscribe": typeof ApiNotificationsPushSubscribeRoute;
  "/oauth/integrations/$provider/callback": typeof OauthIntegrationsProviderCallbackRoute;
  "/api/health/dlq/$id/abandon": typeof ApiHealthDlqIdAbandonRoute;
  "/api/health/dlq/$id/replay": typeof ApiHealthDlqIdReplayRoute;
  "/api/oauth/integrations/$provider/connect": typeof ApiOauthIntegrationsProviderConnectRoute;
}
export interface FileRoutesByTo {
  "/health": typeof HealthRoute;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/search": typeof ApiSearchRoute;
  "/billing/checkout": typeof BillingCheckoutRoute;
  "/billing/extra-usage": typeof BillingExtraUsageRoute;
  "/billing/portal": typeof BillingPortalRoute;
  "/billing/usage": typeof BillingUsageRoute;
  "/mcp/$workspaceId": typeof McpWorkspaceIdRoute;
  "/webhooks/$provider": typeof WebhooksProviderRoute;
  "/webhooks/stripe-billing": typeof WebhooksStripeBillingRoute;
  "/api/automations/generate-prompt": typeof ApiAutomationsGeneratePromptRoute;
  "/api/automations/generate-questions": typeof ApiAutomationsGenerateQuestionsRoute;
  "/api/billing/checkout": typeof ApiBillingCheckoutRoute;
  "/api/billing/extra-usage": typeof ApiBillingExtraUsageRoute;
  "/api/billing/portal": typeof ApiBillingPortalRoute;
  "/api/billing/usage": typeof ApiBillingUsageRoute;
  "/api/health/audit-errors": typeof ApiHealthAuditErrorsRoute;
  "/api/health/deep": typeof ApiHealthDeepRoute;
  "/api/health/dlq": typeof ApiHealthDlqRouteWithChildren;
  "/api/health/flags": typeof ApiHealthFlagsRoute;
  "/api/invites/accept": typeof ApiInvitesAcceptRoute;
  "/api/invites/create": typeof ApiInvitesCreateRoute;
  "/api/mcp/test": typeof ApiMcpTestRoute;
  "/billing/credits/checkout": typeof BillingCreditsCheckoutRoute;
  "/internal/automations/complete": typeof InternalAutomationsCompleteRoute;
  "/internal/automations/dispatch": typeof InternalAutomationsDispatchRoute;
  "/internal/automations/log": typeof InternalAutomationsLogRoute;
  "/internal/automations/terminate": typeof InternalAutomationsTerminateRoute;
  "/internal/cron/maintenance": typeof InternalCronMaintenanceRoute;
  "/internal/notifications/deliver": typeof InternalNotificationsDeliverRoute;
  "/internal/queue/dispatch-approved-action": typeof InternalQueueDispatchApprovedActionRoute;
  "/api/billing/automation-runs/checkout": typeof ApiBillingAutomationRunsCheckoutRoute;
  "/api/billing/credits/checkout": typeof ApiBillingCreditsCheckoutRoute;
  "/api/notifications/push/subscribe": typeof ApiNotificationsPushSubscribeRoute;
  "/oauth/integrations/$provider/callback": typeof OauthIntegrationsProviderCallbackRoute;
  "/api/health/dlq/$id/abandon": typeof ApiHealthDlqIdAbandonRoute;
  "/api/health/dlq/$id/replay": typeof ApiHealthDlqIdReplayRoute;
  "/api/oauth/integrations/$provider/connect": typeof ApiOauthIntegrationsProviderConnectRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/health": typeof HealthRoute;
  "/api/health": typeof ApiHealthRouteWithChildren;
  "/api/search": typeof ApiSearchRoute;
  "/billing/checkout": typeof BillingCheckoutRoute;
  "/billing/extra-usage": typeof BillingExtraUsageRoute;
  "/billing/portal": typeof BillingPortalRoute;
  "/billing/usage": typeof BillingUsageRoute;
  "/mcp/$workspaceId": typeof McpWorkspaceIdRoute;
  "/webhooks/$provider": typeof WebhooksProviderRoute;
  "/webhooks/stripe-billing": typeof WebhooksStripeBillingRoute;
  "/api/automations/generate-prompt": typeof ApiAutomationsGeneratePromptRoute;
  "/api/automations/generate-questions": typeof ApiAutomationsGenerateQuestionsRoute;
  "/api/billing/checkout": typeof ApiBillingCheckoutRoute;
  "/api/billing/extra-usage": typeof ApiBillingExtraUsageRoute;
  "/api/billing/portal": typeof ApiBillingPortalRoute;
  "/api/billing/usage": typeof ApiBillingUsageRoute;
  "/api/health/audit-errors": typeof ApiHealthAuditErrorsRoute;
  "/api/health/deep": typeof ApiHealthDeepRoute;
  "/api/health/dlq": typeof ApiHealthDlqRouteWithChildren;
  "/api/health/flags": typeof ApiHealthFlagsRoute;
  "/api/invites/accept": typeof ApiInvitesAcceptRoute;
  "/api/invites/create": typeof ApiInvitesCreateRoute;
  "/api/mcp/test": typeof ApiMcpTestRoute;
  "/billing/credits/checkout": typeof BillingCreditsCheckoutRoute;
  "/internal/automations/complete": typeof InternalAutomationsCompleteRoute;
  "/internal/automations/dispatch": typeof InternalAutomationsDispatchRoute;
  "/internal/automations/log": typeof InternalAutomationsLogRoute;
  "/internal/automations/terminate": typeof InternalAutomationsTerminateRoute;
  "/internal/cron/maintenance": typeof InternalCronMaintenanceRoute;
  "/internal/notifications/deliver": typeof InternalNotificationsDeliverRoute;
  "/internal/queue/dispatch-approved-action": typeof InternalQueueDispatchApprovedActionRoute;
  "/api/billing/automation-runs/checkout": typeof ApiBillingAutomationRunsCheckoutRoute;
  "/api/billing/credits/checkout": typeof ApiBillingCreditsCheckoutRoute;
  "/api/notifications/push/subscribe": typeof ApiNotificationsPushSubscribeRoute;
  "/oauth/integrations/$provider/callback": typeof OauthIntegrationsProviderCallbackRoute;
  "/api/health/dlq/$id/abandon": typeof ApiHealthDlqIdAbandonRoute;
  "/api/health/dlq/$id/replay": typeof ApiHealthDlqIdReplayRoute;
  "/api/oauth/integrations/$provider/connect": typeof ApiOauthIntegrationsProviderConnectRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/health"
    | "/api/health"
    | "/api/search"
    | "/billing/checkout"
    | "/billing/extra-usage"
    | "/billing/portal"
    | "/billing/usage"
    | "/mcp/$workspaceId"
    | "/webhooks/$provider"
    | "/webhooks/stripe-billing"
    | "/api/automations/generate-prompt"
    | "/api/automations/generate-questions"
    | "/api/billing/checkout"
    | "/api/billing/extra-usage"
    | "/api/billing/portal"
    | "/api/billing/usage"
    | "/api/health/audit-errors"
    | "/api/health/deep"
    | "/api/health/dlq"
    | "/api/health/flags"
    | "/api/invites/accept"
    | "/api/invites/create"
    | "/api/mcp/test"
    | "/billing/credits/checkout"
    | "/internal/automations/complete"
    | "/internal/automations/dispatch"
    | "/internal/automations/log"
    | "/internal/automations/terminate"
    | "/internal/cron/maintenance"
    | "/internal/notifications/deliver"
    | "/internal/queue/dispatch-approved-action"
    | "/api/billing/automation-runs/checkout"
    | "/api/billing/credits/checkout"
    | "/api/notifications/push/subscribe"
    | "/oauth/integrations/$provider/callback"
    | "/api/health/dlq/$id/abandon"
    | "/api/health/dlq/$id/replay"
    | "/api/oauth/integrations/$provider/connect";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/health"
    | "/api/health"
    | "/api/search"
    | "/billing/checkout"
    | "/billing/extra-usage"
    | "/billing/portal"
    | "/billing/usage"
    | "/mcp/$workspaceId"
    | "/webhooks/$provider"
    | "/webhooks/stripe-billing"
    | "/api/automations/generate-prompt"
    | "/api/automations/generate-questions"
    | "/api/billing/checkout"
    | "/api/billing/extra-usage"
    | "/api/billing/portal"
    | "/api/billing/usage"
    | "/api/health/audit-errors"
    | "/api/health/deep"
    | "/api/health/dlq"
    | "/api/health/flags"
    | "/api/invites/accept"
    | "/api/invites/create"
    | "/api/mcp/test"
    | "/billing/credits/checkout"
    | "/internal/automations/complete"
    | "/internal/automations/dispatch"
    | "/internal/automations/log"
    | "/internal/automations/terminate"
    | "/internal/cron/maintenance"
    | "/internal/notifications/deliver"
    | "/internal/queue/dispatch-approved-action"
    | "/api/billing/automation-runs/checkout"
    | "/api/billing/credits/checkout"
    | "/api/notifications/push/subscribe"
    | "/oauth/integrations/$provider/callback"
    | "/api/health/dlq/$id/abandon"
    | "/api/health/dlq/$id/replay"
    | "/api/oauth/integrations/$provider/connect";
  id:
    | "__root__"
    | "/health"
    | "/api/health"
    | "/api/search"
    | "/billing/checkout"
    | "/billing/extra-usage"
    | "/billing/portal"
    | "/billing/usage"
    | "/mcp/$workspaceId"
    | "/webhooks/$provider"
    | "/webhooks/stripe-billing"
    | "/api/automations/generate-prompt"
    | "/api/automations/generate-questions"
    | "/api/billing/checkout"
    | "/api/billing/extra-usage"
    | "/api/billing/portal"
    | "/api/billing/usage"
    | "/api/health/audit-errors"
    | "/api/health/deep"
    | "/api/health/dlq"
    | "/api/health/flags"
    | "/api/invites/accept"
    | "/api/invites/create"
    | "/api/mcp/test"
    | "/billing/credits/checkout"
    | "/internal/automations/complete"
    | "/internal/automations/dispatch"
    | "/internal/automations/log"
    | "/internal/automations/terminate"
    | "/internal/cron/maintenance"
    | "/internal/notifications/deliver"
    | "/internal/queue/dispatch-approved-action"
    | "/api/billing/automation-runs/checkout"
    | "/api/billing/credits/checkout"
    | "/api/notifications/push/subscribe"
    | "/oauth/integrations/$provider/callback"
    | "/api/health/dlq/$id/abandon"
    | "/api/health/dlq/$id/replay"
    | "/api/oauth/integrations/$provider/connect";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  HealthRoute: typeof HealthRoute;
  ApiHealthRoute: typeof ApiHealthRouteWithChildren;
  ApiSearchRoute: typeof ApiSearchRoute;
  BillingCheckoutRoute: typeof BillingCheckoutRoute;
  BillingExtraUsageRoute: typeof BillingExtraUsageRoute;
  BillingPortalRoute: typeof BillingPortalRoute;
  BillingUsageRoute: typeof BillingUsageRoute;
  McpWorkspaceIdRoute: typeof McpWorkspaceIdRoute;
  WebhooksProviderRoute: typeof WebhooksProviderRoute;
  WebhooksStripeBillingRoute: typeof WebhooksStripeBillingRoute;
  ApiAutomationsGeneratePromptRoute: typeof ApiAutomationsGeneratePromptRoute;
  ApiAutomationsGenerateQuestionsRoute: typeof ApiAutomationsGenerateQuestionsRoute;
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute;
  ApiBillingExtraUsageRoute: typeof ApiBillingExtraUsageRoute;
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute;
  ApiBillingUsageRoute: typeof ApiBillingUsageRoute;
  ApiInvitesAcceptRoute: typeof ApiInvitesAcceptRoute;
  ApiInvitesCreateRoute: typeof ApiInvitesCreateRoute;
  ApiMcpTestRoute: typeof ApiMcpTestRoute;
  BillingCreditsCheckoutRoute: typeof BillingCreditsCheckoutRoute;
  InternalAutomationsCompleteRoute: typeof InternalAutomationsCompleteRoute;
  InternalAutomationsDispatchRoute: typeof InternalAutomationsDispatchRoute;
  InternalAutomationsLogRoute: typeof InternalAutomationsLogRoute;
  InternalAutomationsTerminateRoute: typeof InternalAutomationsTerminateRoute;
  InternalCronMaintenanceRoute: typeof InternalCronMaintenanceRoute;
  InternalNotificationsDeliverRoute: typeof InternalNotificationsDeliverRoute;
  InternalQueueDispatchApprovedActionRoute: typeof InternalQueueDispatchApprovedActionRoute;
  ApiBillingAutomationRunsCheckoutRoute: typeof ApiBillingAutomationRunsCheckoutRoute;
  ApiBillingCreditsCheckoutRoute: typeof ApiBillingCreditsCheckoutRoute;
  ApiNotificationsPushSubscribeRoute: typeof ApiNotificationsPushSubscribeRoute;
  OauthIntegrationsProviderCallbackRoute: typeof OauthIntegrationsProviderCallbackRoute;
  ApiOauthIntegrationsProviderConnectRoute: typeof ApiOauthIntegrationsProviderConnectRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/health": {
      id: "/health";
      path: "/health";
      fullPath: "/health";
      preLoaderRoute: typeof HealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/webhooks/stripe-billing": {
      id: "/webhooks/stripe-billing";
      path: "/webhooks/stripe-billing";
      fullPath: "/webhooks/stripe-billing";
      preLoaderRoute: typeof WebhooksStripeBillingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/webhooks/$provider": {
      id: "/webhooks/$provider";
      path: "/webhooks/$provider";
      fullPath: "/webhooks/$provider";
      preLoaderRoute: typeof WebhooksProviderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mcp/$workspaceId": {
      id: "/mcp/$workspaceId";
      path: "/mcp/$workspaceId";
      fullPath: "/mcp/$workspaceId";
      preLoaderRoute: typeof McpWorkspaceIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing/usage": {
      id: "/billing/usage";
      path: "/billing/usage";
      fullPath: "/billing/usage";
      preLoaderRoute: typeof BillingUsageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing/portal": {
      id: "/billing/portal";
      path: "/billing/portal";
      fullPath: "/billing/portal";
      preLoaderRoute: typeof BillingPortalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing/extra-usage": {
      id: "/billing/extra-usage";
      path: "/billing/extra-usage";
      fullPath: "/billing/extra-usage";
      preLoaderRoute: typeof BillingExtraUsageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing/checkout": {
      id: "/billing/checkout";
      path: "/billing/checkout";
      fullPath: "/billing/checkout";
      preLoaderRoute: typeof BillingCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/queue/dispatch-approved-action": {
      id: "/internal/queue/dispatch-approved-action";
      path: "/internal/queue/dispatch-approved-action";
      fullPath: "/internal/queue/dispatch-approved-action";
      preLoaderRoute: typeof InternalQueueDispatchApprovedActionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/notifications/deliver": {
      id: "/internal/notifications/deliver";
      path: "/internal/notifications/deliver";
      fullPath: "/internal/notifications/deliver";
      preLoaderRoute: typeof InternalNotificationsDeliverRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/cron/maintenance": {
      id: "/internal/cron/maintenance";
      path: "/internal/cron/maintenance";
      fullPath: "/internal/cron/maintenance";
      preLoaderRoute: typeof InternalCronMaintenanceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/automations/terminate": {
      id: "/internal/automations/terminate";
      path: "/internal/automations/terminate";
      fullPath: "/internal/automations/terminate";
      preLoaderRoute: typeof InternalAutomationsTerminateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/automations/log": {
      id: "/internal/automations/log";
      path: "/internal/automations/log";
      fullPath: "/internal/automations/log";
      preLoaderRoute: typeof InternalAutomationsLogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/automations/dispatch": {
      id: "/internal/automations/dispatch";
      path: "/internal/automations/dispatch";
      fullPath: "/internal/automations/dispatch";
      preLoaderRoute: typeof InternalAutomationsDispatchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/internal/automations/complete": {
      id: "/internal/automations/complete";
      path: "/internal/automations/complete";
      fullPath: "/internal/automations/complete";
      preLoaderRoute: typeof InternalAutomationsCompleteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/billing/credits/checkout": {
      id: "/billing/credits/checkout";
      path: "/billing/credits/checkout";
      fullPath: "/billing/credits/checkout";
      preLoaderRoute: typeof BillingCreditsCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/mcp/test": {
      id: "/api/mcp/test";
      path: "/api/mcp/test";
      fullPath: "/api/mcp/test";
      preLoaderRoute: typeof ApiMcpTestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/invites/create": {
      id: "/api/invites/create";
      path: "/api/invites/create";
      fullPath: "/api/invites/create";
      preLoaderRoute: typeof ApiInvitesCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/invites/accept": {
      id: "/api/invites/accept";
      path: "/api/invites/accept";
      fullPath: "/api/invites/accept";
      preLoaderRoute: typeof ApiInvitesAcceptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health/flags": {
      id: "/api/health/flags";
      path: "/flags";
      fullPath: "/api/health/flags";
      preLoaderRoute: typeof ApiHealthFlagsRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
    "/api/health/dlq": {
      id: "/api/health/dlq";
      path: "/dlq";
      fullPath: "/api/health/dlq";
      preLoaderRoute: typeof ApiHealthDlqRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
    "/api/health/deep": {
      id: "/api/health/deep";
      path: "/deep";
      fullPath: "/api/health/deep";
      preLoaderRoute: typeof ApiHealthDeepRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
    "/api/health/audit-errors": {
      id: "/api/health/audit-errors";
      path: "/audit-errors";
      fullPath: "/api/health/audit-errors";
      preLoaderRoute: typeof ApiHealthAuditErrorsRouteImport;
      parentRoute: typeof ApiHealthRoute;
    };
    "/api/billing/usage": {
      id: "/api/billing/usage";
      path: "/api/billing/usage";
      fullPath: "/api/billing/usage";
      preLoaderRoute: typeof ApiBillingUsageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/billing/portal": {
      id: "/api/billing/portal";
      path: "/api/billing/portal";
      fullPath: "/api/billing/portal";
      preLoaderRoute: typeof ApiBillingPortalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/billing/extra-usage": {
      id: "/api/billing/extra-usage";
      path: "/api/billing/extra-usage";
      fullPath: "/api/billing/extra-usage";
      preLoaderRoute: typeof ApiBillingExtraUsageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/billing/checkout": {
      id: "/api/billing/checkout";
      path: "/api/billing/checkout";
      fullPath: "/api/billing/checkout";
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/automations/generate-questions": {
      id: "/api/automations/generate-questions";
      path: "/api/automations/generate-questions";
      fullPath: "/api/automations/generate-questions";
      preLoaderRoute: typeof ApiAutomationsGenerateQuestionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/automations/generate-prompt": {
      id: "/api/automations/generate-prompt";
      path: "/api/automations/generate-prompt";
      fullPath: "/api/automations/generate-prompt";
      preLoaderRoute: typeof ApiAutomationsGeneratePromptRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/oauth/integrations/$provider/callback": {
      id: "/oauth/integrations/$provider/callback";
      path: "/oauth/integrations/$provider/callback";
      fullPath: "/oauth/integrations/$provider/callback";
      preLoaderRoute: typeof OauthIntegrationsProviderCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/notifications/push/subscribe": {
      id: "/api/notifications/push/subscribe";
      path: "/api/notifications/push/subscribe";
      fullPath: "/api/notifications/push/subscribe";
      preLoaderRoute: typeof ApiNotificationsPushSubscribeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/billing/credits/checkout": {
      id: "/api/billing/credits/checkout";
      path: "/api/billing/credits/checkout";
      fullPath: "/api/billing/credits/checkout";
      preLoaderRoute: typeof ApiBillingCreditsCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/billing/automation-runs/checkout": {
      id: "/api/billing/automation-runs/checkout";
      path: "/api/billing/automation-runs/checkout";
      fullPath: "/api/billing/automation-runs/checkout";
      preLoaderRoute: typeof ApiBillingAutomationRunsCheckoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/oauth/integrations/$provider/connect": {
      id: "/api/oauth/integrations/$provider/connect";
      path: "/api/oauth/integrations/$provider/connect";
      fullPath: "/api/oauth/integrations/$provider/connect";
      preLoaderRoute: typeof ApiOauthIntegrationsProviderConnectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health/dlq/$id/replay": {
      id: "/api/health/dlq/$id/replay";
      path: "/$id/replay";
      fullPath: "/api/health/dlq/$id/replay";
      preLoaderRoute: typeof ApiHealthDlqIdReplayRouteImport;
      parentRoute: typeof ApiHealthDlqRoute;
    };
    "/api/health/dlq/$id/abandon": {
      id: "/api/health/dlq/$id/abandon";
      path: "/$id/abandon";
      fullPath: "/api/health/dlq/$id/abandon";
      preLoaderRoute: typeof ApiHealthDlqIdAbandonRouteImport;
      parentRoute: typeof ApiHealthDlqRoute;
    };
  }
}

interface ApiHealthDlqRouteChildren {
  ApiHealthDlqIdAbandonRoute: typeof ApiHealthDlqIdAbandonRoute;
  ApiHealthDlqIdReplayRoute: typeof ApiHealthDlqIdReplayRoute;
}

const ApiHealthDlqRouteChildren: ApiHealthDlqRouteChildren = {
  ApiHealthDlqIdAbandonRoute: ApiHealthDlqIdAbandonRoute,
  ApiHealthDlqIdReplayRoute: ApiHealthDlqIdReplayRoute,
};

const ApiHealthDlqRouteWithChildren = ApiHealthDlqRoute._addFileChildren(
  ApiHealthDlqRouteChildren,
);

interface ApiHealthRouteChildren {
  ApiHealthAuditErrorsRoute: typeof ApiHealthAuditErrorsRoute;
  ApiHealthDeepRoute: typeof ApiHealthDeepRoute;
  ApiHealthDlqRoute: typeof ApiHealthDlqRouteWithChildren;
  ApiHealthFlagsRoute: typeof ApiHealthFlagsRoute;
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthAuditErrorsRoute: ApiHealthAuditErrorsRoute,
  ApiHealthDeepRoute: ApiHealthDeepRoute,
  ApiHealthDlqRoute: ApiHealthDlqRouteWithChildren,
  ApiHealthFlagsRoute: ApiHealthFlagsRoute,
};

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  HealthRoute: HealthRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingExtraUsageRoute: BillingExtraUsageRoute,
  BillingPortalRoute: BillingPortalRoute,
  BillingUsageRoute: BillingUsageRoute,
  McpWorkspaceIdRoute: McpWorkspaceIdRoute,
  WebhooksProviderRoute: WebhooksProviderRoute,
  WebhooksStripeBillingRoute: WebhooksStripeBillingRoute,
  ApiAutomationsGeneratePromptRoute: ApiAutomationsGeneratePromptRoute,
  ApiAutomationsGenerateQuestionsRoute: ApiAutomationsGenerateQuestionsRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingExtraUsageRoute: ApiBillingExtraUsageRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingUsageRoute: ApiBillingUsageRoute,
  ApiInvitesAcceptRoute: ApiInvitesAcceptRoute,
  ApiInvitesCreateRoute: ApiInvitesCreateRoute,
  ApiMcpTestRoute: ApiMcpTestRoute,
  BillingCreditsCheckoutRoute: BillingCreditsCheckoutRoute,
  InternalAutomationsCompleteRoute: InternalAutomationsCompleteRoute,
  InternalAutomationsDispatchRoute: InternalAutomationsDispatchRoute,
  InternalAutomationsLogRoute: InternalAutomationsLogRoute,
  InternalAutomationsTerminateRoute: InternalAutomationsTerminateRoute,
  InternalCronMaintenanceRoute: InternalCronMaintenanceRoute,
  InternalNotificationsDeliverRoute: InternalNotificationsDeliverRoute,
  InternalQueueDispatchApprovedActionRoute:
    InternalQueueDispatchApprovedActionRoute,
  ApiBillingAutomationRunsCheckoutRoute: ApiBillingAutomationRunsCheckoutRoute,
  ApiBillingCreditsCheckoutRoute: ApiBillingCreditsCheckoutRoute,
  ApiNotificationsPushSubscribeRoute: ApiNotificationsPushSubscribeRoute,
  OauthIntegrationsProviderCallbackRoute:
    OauthIntegrationsProviderCallbackRoute,
  ApiOauthIntegrationsProviderConnectRoute:
    ApiOauthIntegrationsProviderConnectRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "../src/router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
