import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const githubTools: ToolDefinition[] = [
  {
    name: "github.listIssues",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_issues",
    description: "List GitHub issues",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      state: z.enum(["open", "closed", "all"]).default("open"),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getIssue",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_issue",
    description: "Get GitHub issue",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
    }),
  },
  {
    name: "github.listIssueEvents",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_issue_events",
    description: "List GitHub issue events",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listIssueTimeline",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_issue_timeline",
    description: "List GitHub issue timeline events",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listPullRequests",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_pull_requests",
    description: "List GitHub pull requests",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      state: z.enum(["open", "closed", "all"]).default("open"),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getPullRequest",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_pull_request",
    description: "Get GitHub pull request",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
    }),
  },
  {
    name: "github.listPRFiles",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_pr_files",
    description: "List GitHub pull request files",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(50),
    }),
  },
  {
    name: "github.searchIssues",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_issues",
    description: "Search GitHub issues and pull requests",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      query: z.string().default(""),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.searchCode",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_code",
    description: "Search GitHub code",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.searchRepositories",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_repositories",
    description: "Search GitHub repositories",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getRepo",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_repo",
    description: "Get GitHub repository details",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
    }),
  },
  {
    name: "github.listOrgRepos",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_org_repos",
    description: "List organization repositories",
    redaction_policy: [],
    input_schema: z.object({
      org: z.string().min(1),
      type: z.enum(["all", "public", "private", "forks", "sources", "member"]).default("all"),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listReviews",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_reviews",
    description: "List GitHub pull request reviews",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listCommits",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_commits",
    description: "List GitHub repository commits",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
      sha: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.compareCommits",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "compare_commits",
    description: "Compare two GitHub refs",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      base: z.string().min(1),
      head: z.string().min(1),
    }),
  },
  {
    name: "github.getCommitStatus",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_commit_status",
    description: "Get combined commit status",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      ref: z.string().min(1),
    }),
  },
  {
    name: "github.listCheckRuns",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_check_runs",
    description: "List check runs for a commit",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      ref: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listWorkflowRuns",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_workflow_runs",
    description: "List GitHub workflow runs",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
      branch: z.string().min(1).optional(),
      status: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.getWorkflowRun",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_workflow_run",
    description: "Get GitHub workflow run details",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      runId: z.number().int().positive(),
    }),
  },
  {
    name: "github.listNotifications",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_notifications",
    description: "List authenticated user notifications",
    redaction_policy: [],
    input_schema: z.object({
      all: z.boolean().default(false),
      participating: z.boolean().default(false),
      since: z.string().datetime().optional(),
      before: z.string().datetime().optional(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getWorkflowJobLogs",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_workflow_job_logs",
    description: "Get GitHub workflow job logs download metadata",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      jobId: z.number().int().positive(),
    }),
  },
  {
    name: "github.listPRCommits",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_pr_commits",
    description: "List pull request commits",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listIssueComments",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_issue_comments",
    description: "List issue comments",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getLatestRelease",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_latest_release",
    description: "Get latest repository release",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
    }),
  },
  {
    name: "github.listReleases",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_releases",
    description: "List repository releases",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listMilestones",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_milestones",
    description: "List repository milestones",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      state: z.enum(["open", "closed", "all"]).default("open"),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.listBranches",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_branches",
    description: "List repository branches",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.getFileContents",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_file_contents",
    description: "Get repository file contents",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      path: z.string().min(1),
      ref: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.listLabels",
    provider: "github",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_labels",
    description: "List repository labels",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      perPage: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "github.createOrUpdateFile",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_or_update_file",
    description: "Create or update repository file",
    redaction_policy: ["content", "message"],
    input_schema: z.object({
      repo: z.string().min(1),
      path: z.string().min(1),
      message: z.string().min(1),
      content: z.string(),
      sha: z.string().min(1).optional(),
      branch: z.string().min(1).optional(),
      committerName: z.string().min(1).optional(),
      committerEmail: z.string().email().optional(),
      authorName: z.string().min(1).optional(),
      authorEmail: z.string().email().optional(),
    }),
  },
  {
    name: "github.createLabel",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_label",
    description: "Create repository label",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      name: z.string().min(1),
      color: z.string().regex(/^[0-9a-fA-F]{6}$/, "color must be a 6-character hex value"),
      description: z.string().optional(),
    }),
  },
  {
    name: "github.createRelease",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_release",
    description: "Create repository release",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      tagName: z.string().min(1),
      targetCommitish: z.string().min(1).optional(),
      name: z.string().optional(),
      body: z.string().optional(),
      draft: z.boolean().default(false),
      prerelease: z.boolean().default(false),
      generateReleaseNotes: z.boolean().default(false),
    }),
  },
  {
    name: "github.updateRelease",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_release",
    description: "Update repository release",
    redaction_policy: ["body"],
    input_schema: z
      .object({
        repo: z.string().min(1),
        releaseId: z.number().int().positive(),
        tagName: z.string().min(1).optional(),
        targetCommitish: z.string().min(1).optional(),
        name: z.string().optional(),
        body: z.string().optional(),
        draft: z.boolean().optional(),
        prerelease: z.boolean().optional(),
      })
      .refine(
        (value) =>
          value.tagName !== undefined ||
          value.targetCommitish !== undefined ||
          value.name !== undefined ||
          value.body !== undefined ||
          value.draft !== undefined ||
          value.prerelease !== undefined,
        {
          message:
            "At least one of tagName, targetCommitish, name, body, draft, or prerelease must be provided.",
        },
      ),
  },
  {
    name: "github.generateReleaseNotes",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "generate_release_notes",
    description: "Generate release notes",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      tagName: z.string().min(1),
      targetCommitish: z.string().min(1).optional(),
      previousTagName: z.string().min(1).optional(),
      configurationFilePath: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.createMilestone",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_milestone",
    description: "Create repository milestone",
    redaction_policy: ["description"],
    input_schema: z.object({
      repo: z.string().min(1),
      title: z.string().min(1),
      state: z.enum(["open", "closed"]).default("open"),
      description: z.string().optional(),
      dueOn: z.string().optional(),
    }),
  },
  {
    name: "github.updateMilestone",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "update_milestone",
    description: "Update repository milestone",
    redaction_policy: ["description"],
    input_schema: z
      .object({
        repo: z.string().min(1),
        milestone: z.number().int().positive(),
        title: z.string().min(1).optional(),
        state: z.enum(["open", "closed"]).optional(),
        description: z.string().optional(),
        dueOn: z.string().optional(),
      })
      .refine(
        (value) =>
          value.title !== undefined ||
          value.state !== undefined ||
          value.description !== undefined ||
          value.dueOn !== undefined,
        {
          message: "At least one of title, state, description, or dueOn must be provided.",
        },
      ),
  },
  {
    name: "github.commentIssue",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "comment_issue",
    description: "Comment on GitHub issue",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      body: z.string().min(1),
    }),
  },
  {
    name: "github.lockIssue",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "lock_issue",
    description: "Lock GitHub issue conversation",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      lockReason: z.enum(["off-topic", "too heated", "resolved", "spam"]).optional(),
    }),
  },
  {
    name: "github.unlockIssue",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unlock_issue",
    description: "Unlock GitHub issue conversation",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
    }),
  },
  {
    name: "github.createIssue",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_issue",
    description: "Create GitHub issue",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      title: z.string().min(1),
      body: z.string().default(""),
      labels: z.array(z.string().min(1)).max(20).default([]),
      assignees: z.array(z.string().min(1)).max(20).default([]),
    }),
  },
  {
    name: "github.updateIssue",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_issue",
    description: "Update GitHub issue",
    redaction_policy: ["body"],
    input_schema: z
      .object({
        repo: z.string().min(1),
        issue: z.number().int().positive(),
        title: z.string().min(1).optional(),
        body: z.string().optional(),
        state: z.enum(["open", "closed"]).optional(),
        labels: z.array(z.string().min(1)).max(20).optional(),
        assignees: z.array(z.string().min(1)).max(20).optional(),
      })
      .refine(
        (value) =>
          value.title !== undefined ||
          value.body !== undefined ||
          value.state !== undefined ||
          value.labels !== undefined ||
          value.assignees !== undefined,
        {
          message: "At least one of title, body, state, labels, or assignees must be provided.",
        },
      ),
  },
  {
    name: "github.createPullRequest",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_pull_request",
    description: "Create GitHub pull request",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      title: z.string().min(1),
      head: z.string().min(1),
      base: z.string().min(1),
      body: z.string().default(""),
    }),
  },
  {
    name: "github.mergePullRequest",
    provider: "github",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "merge_pull_request",
    description: "Merge GitHub pull request",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      mergeMethod: z.enum(["merge", "squash", "rebase"]).default("merge"),
      commitTitle: z.string().optional(),
    }),
  },
  {
    name: "github.addLabels",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_labels",
    description: "Add GitHub issue or pull request labels",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      labels: z.array(z.string().min(1)).min(1).max(20),
    }),
  },
  {
    name: "github.removeLabel",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_label",
    description: "Remove GitHub issue or pull request label",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      label: z.string().min(1),
    }),
  },
  {
    name: "github.addAssignees",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_assignees",
    description: "Add GitHub issue assignees",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      assignees: z.array(z.string().min(1)).min(1).max(20),
    }),
  },
  {
    name: "github.removeAssignees",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_assignees",
    description: "Remove GitHub issue assignees",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      assignees: z.array(z.string().min(1)).min(1).max(20),
    }),
  },
  {
    name: "github.createReview",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_review",
    description: "Create pull request review",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      event: z.enum(["APPROVE", "REQUEST_CHANGES", "COMMENT"]).default("COMMENT"),
      body: z.string().min(1).optional(),
      commitId: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.dismissReview",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "dismiss_review",
    description: "Dismiss pull request review",
    redaction_policy: ["message"],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      reviewId: z.number().int().positive(),
      message: z.string().min(1),
    }),
  },
  {
    name: "github.requestReviewers",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "request_reviewers",
    description: "Request pull request reviewers",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      reviewers: z.array(z.string().min(1)).min(1).max(20),
    }),
  },
  {
    name: "github.removeReviewers",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_reviewers",
    description: "Remove requested pull request reviewers",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      reviewers: z.array(z.string().min(1)).min(1).max(20),
    }),
  },
  {
    name: "github.createReviewComment",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_review_comment",
    description: "Create pull request review comment",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      body: z.string().min(1),
      commitId: z.string().min(1).optional(),
      path: z.string().min(1),
      line: z.number().int().positive(),
    }),
  },
  {
    name: "github.triggerWorkflow",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "trigger_workflow",
    description: "Trigger GitHub workflow run",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      workflowId: z.string().min(1),
      ref: z.string().min(1),
      inputs: z.record(z.string(), z.string()).default({}),
    }),
  },
  {
    name: "github.cancelWorkflowRun",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "cancel_workflow_run",
    description: "Cancel workflow run",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      runId: z.number().int().positive(),
    }),
  },
  {
    name: "github.rerunWorkflow",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "rerun_workflow",
    description: "Re-run workflow run",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      runId: z.number().int().positive(),
      enableDebugLogging: z.boolean().default(false),
    }),
  },
  {
    name: "github.markNotificationsRead",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "mark_notifications_read",
    description: "Mark GitHub notifications as read",
    redaction_policy: [],
    input_schema: z.object({
      lastReadAt: z.string().datetime().optional(),
    }),
  },
  {
    name: "github.rerunFailedJobs",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "rerun_failed_jobs",
    description: "Re-run failed jobs in a workflow run",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      runId: z.number().int().positive(),
      enableDebugLogging: z.boolean().default(false),
    }),
  },
  {
    name: "github.updatePRBranch",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "update_pr_branch",
    description: "Update pull request branch from base branch",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      pullNumber: z.number().int().positive(),
      expectedHeadSha: z.string().min(1).optional(),
    }),
  },
  {
    name: "github.createReaction",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_reaction",
    description: "Create reaction on an issue",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      content: z.enum(["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]),
    }),
  },
  {
    name: "github.deleteReaction",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_reaction",
    description: "Delete a reaction from an issue",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      issue: z.number().int().positive(),
      reactionId: z.number().int().positive(),
    }),
  },
  {
    name: "github.createDispatchEvent",
    provider: "github",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_dispatch_event",
    description: "Create repository dispatch event",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      eventType: z.string().min(1),
      clientPayload: z.record(z.string(), z.unknown()).default({}),
    }),
  },
  {
    name: "github.updatePullRequest",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_pull_request",
    description: "Update pull request",
    redaction_policy: ["body"],
    input_schema: z
      .object({
        repo: z.string().min(1),
        pullNumber: z.number().int().positive(),
        title: z.string().min(1).optional(),
        body: z.string().optional(),
        state: z.enum(["open", "closed"]).optional(),
        base: z.string().min(1).optional(),
      })
      .refine(
        (value) =>
          value.title !== undefined ||
          value.body !== undefined ||
          value.state !== undefined ||
          value.base !== undefined,
        {
          message: "At least one of title, body, state, or base must be provided.",
        },
      ),
  },
  {
    name: "github.updateComment",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_comment",
    description: "Update issue comment",
    redaction_policy: ["body"],
    input_schema: z.object({
      repo: z.string().min(1),
      commentId: z.number().int().positive(),
      body: z.string().min(1),
    }),
  },
  {
    name: "github.deleteComment",
    provider: "github",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_comment",
    description: "Delete issue comment",
    redaction_policy: [],
    input_schema: z.object({
      repo: z.string().min(1),
      commentId: z.number().int().positive(),
    }),
  },
];
