import { z } from "zod";
import type { ToolDefinition } from "./types.js";

const emailSchema = z.string().email();
const gmailFilterCriteriaSchema = z
  .object({
    from: z.string().min(1).optional(),
    to: z.string().min(1).optional(),
    subject: z.string().min(1).optional(),
    query: z.string().min(1).optional(),
    negatedQuery: z.string().min(1).optional(),
    hasAttachment: z.boolean().optional(),
    sizeComparison: z.enum(["larger", "smaller"]).optional(),
    size: z.number().int().min(1).optional(),
  })
  .refine((value) => Object.keys(value).length > 0, {
    message: "At least one criteria field must be provided.",
  });
const gmailFilterActionSchema = z
  .object({
    addLabelIds: z.array(z.string().min(1)).default([]),
    removeLabelIds: z.array(z.string().min(1)).default([]),
    forward: emailSchema.optional(),
  })
  .refine(
    (value) => value.addLabelIds.length > 0 || value.removeLabelIds.length > 0 || !!value.forward,
    {
      message: "At least one action field must be provided.",
    },
  );
const gmailVacationSettingsSchema = z.object({
  enableAutoReply: z.boolean(),
  responseSubject: z.string().default(""),
  responseBodyPlainText: z.string().default(""),
  responseBodyHtml: z.string().default(""),
  restrictToContacts: z.boolean().default(false),
  restrictToDomain: z.boolean().default(false),
  startTime: z.string().min(1).optional(),
  endTime: z.string().min(1).optional(),
});
const gmailUpdateLabelSchema = z
  .object({
    labelId: z.string().min(1),
    name: z.string().min(1).optional(),
    labelListVisibility: z.enum(["labelShow", "labelShowIfUnread", "labelHide"]).optional(),
    messageListVisibility: z.enum(["show", "hide"]).optional(),
  })
  .refine(
    (value) =>
      typeof value.name === "string" ||
      typeof value.labelListVisibility === "string" ||
      typeof value.messageListVisibility === "string",
    { message: "At least one label field must be provided." },
  );
const gmailUpdateSendAsAliasSchema = z
  .object({
    sendAsEmail: emailSchema,
    displayName: z.string().min(1).optional(),
    replyToAddress: emailSchema.optional(),
    signature: z.string().min(1).optional(),
    treatAsAlias: z.boolean().optional(),
  })
  .refine(
    (value) =>
      typeof value.displayName === "string" ||
      typeof value.replyToAddress === "string" ||
      typeof value.signature === "string" ||
      typeof value.treatAsAlias === "boolean",
    { message: "At least one alias field must be provided." },
  );

export const gmailTools: ToolDefinition[] = [
  {
    name: "gmail.searchThreads",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_threads",
    description: "Search Gmail threads",
    redaction_policy: ["body", "snippet", "to", "from", "email"],
    input_schema: z.object({
      query: z.string().default(""),
      limit: z.number().int().min(1).max(50).default(20),
    }),
  },
  {
    name: "gmail.listUnread",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_unread",
    description: "List unread Gmail threads",
    redaction_policy: ["body", "snippet", "to", "from", "email"],
    input_schema: z.object({ limit: z.number().int().min(1).max(50).default(20) }),
  },
  {
    name: "gmail.fetchMessageBody",
    provider: "google",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "fetch_message",
    description: "Fetch message body",
    redaction_policy: ["body", "to", "from", "email"],
    input_schema: z.object({ messageId: z.string().min(1) }),
  },
  {
    name: "gmail.fetchAttachmentsMetadata",
    provider: "google",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "fetch_attachments",
    description: "Fetch attachment metadata",
    redaction_policy: ["filename", "email"],
    input_schema: z.object({ messageId: z.string().min(1) }),
  },
  {
    name: "gmail.sendEmail",
    provider: "google",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "send_email",
    description: "Send an email",
    redaction_policy: ["body", "to", "cc", "bcc", "from", "email"],
    input_schema: z.object({
      to: z.array(emailSchema).min(1),
      cc: z.array(emailSchema).default([]),
      bcc: z.array(emailSchema).default([]),
      subject: z.string().min(1),
      body: z.string().min(1),
    }),
  },
  {
    name: "gmail.replyToThread",
    provider: "google",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "reply_email",
    description: "Reply to an email thread",
    redaction_policy: ["body", "to", "email"],
    input_schema: z.object({
      threadId: z.string().min(1),
      to: z.array(emailSchema).default([]),
      body: z.string().min(1),
    }),
  },
  {
    name: "gmail.applyLabel",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "apply_label",
    description: "Apply a Gmail label",
    redaction_policy: ["label"],
    input_schema: z.object({ threadId: z.string().min(1), label: z.string().min(1) }),
  },
  {
    name: "gmail.archive",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "archive_thread",
    description: "Archive a Gmail thread",
    redaction_policy: [],
    input_schema: z.object({ threadId: z.string().min(1) }),
  },
  {
    name: "gmail.getProfile",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_profile",
    description: "Get Gmail account profile",
    redaction_policy: ["email"],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.getThread",
    provider: "google",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_thread",
    description: "Get full Gmail thread",
    redaction_policy: ["body", "to", "from", "email"],
    input_schema: z.object({ threadId: z.string().min(1) }),
  },
  {
    name: "gmail.listLabels",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_labels",
    description: "List Gmail labels",
    redaction_policy: [],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.createLabel",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_label",
    description: "Create Gmail label",
    redaction_policy: ["label", "name"],
    input_schema: z.object({
      name: z.string().min(1),
      labelListVisibility: z
        .enum(["labelShow", "labelShowIfUnread", "labelHide"])
        .default("labelShow"),
      messageListVisibility: z.enum(["show", "hide"]).default("show"),
    }),
  },
  {
    name: "gmail.createDraft",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_draft",
    description: "Create Gmail draft",
    redaction_policy: ["body", "to", "cc", "bcc", "email"],
    input_schema: z.object({
      to: z.array(emailSchema).min(1),
      cc: z.array(emailSchema).default([]),
      bcc: z.array(emailSchema).default([]),
      subject: z.string().min(1),
      body: z.string().min(1),
      threadId: z.string().min(1).optional(),
    }),
  },
  {
    name: "gmail.listDrafts",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_drafts",
    description: "List Gmail drafts",
    redaction_policy: [],
    input_schema: z.object({ limit: z.number().int().min(1).max(50).default(20) }),
  },
  {
    name: "gmail.getDraft",
    provider: "google",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_draft",
    description: "Get Gmail draft",
    redaction_policy: ["body", "to", "email"],
    input_schema: z.object({ draftId: z.string().min(1) }),
  },
  {
    name: "gmail.updateDraft",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_draft",
    description: "Update Gmail draft",
    redaction_policy: ["body", "to", "cc", "bcc", "email"],
    input_schema: z.object({
      draftId: z.string().min(1),
      to: z.array(emailSchema).min(1),
      cc: z.array(emailSchema).default([]),
      bcc: z.array(emailSchema).default([]),
      subject: z.string().min(1),
      body: z.string().min(1),
      threadId: z.string().min(1).optional(),
    }),
  },
  {
    name: "gmail.sendDraft",
    provider: "google",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "send_draft",
    description: "Send Gmail draft",
    redaction_policy: [],
    input_schema: z.object({ draftId: z.string().min(1) }),
  },
  {
    name: "gmail.batchModifyMessages",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "batch_modify_messages",
    description: "Batch modify Gmail message labels",
    redaction_policy: ["label"],
    input_schema: z
      .object({
        messageIds: z.array(z.string().min(1)).min(1).max(100),
        addLabelIds: z.array(z.string().min(1)).default([]),
        removeLabelIds: z.array(z.string().min(1)).default([]),
      })
      .refine((value) => value.addLabelIds.length > 0 || value.removeLabelIds.length > 0, {
        message: "At least one of addLabelIds or removeLabelIds must be provided.",
      }),
  },
  {
    name: "gmail.listHistory",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_history",
    description: "List Gmail history records",
    redaction_policy: [],
    input_schema: z.object({
      startHistoryId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
      labelId: z.string().min(1).optional(),
    }),
  },
  {
    name: "gmail.watch",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "watch_mailbox",
    description: "Start Gmail mailbox watch",
    redaction_policy: [],
    input_schema: z.object({
      topicName: z.string().min(1),
      labelIds: z.array(z.string().min(1)).default([]),
      labelFilterBehavior: z.enum(["include", "exclude"]).default("include"),
    }),
  },
  {
    name: "gmail.stopWatch",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "stop_watch",
    description: "Stop Gmail mailbox watch",
    redaction_policy: [],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.trashThread",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "trash_thread",
    description: "Move Gmail thread to trash",
    redaction_policy: [],
    input_schema: z.object({ threadId: z.string().min(1) }),
  },
  {
    name: "gmail.untrashThread",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "untrash_thread",
    description: "Restore Gmail thread from trash",
    redaction_policy: [],
    input_schema: z.object({ threadId: z.string().min(1) }),
  },
  {
    name: "gmail.trashMessage",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "trash_message",
    description: "Move Gmail message to trash",
    redaction_policy: [],
    input_schema: z.object({ messageId: z.string().min(1) }),
  },
  {
    name: "gmail.untrashMessage",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "untrash_message",
    description: "Restore Gmail message from trash",
    redaction_policy: [],
    input_schema: z.object({ messageId: z.string().min(1) }),
  },
  {
    name: "gmail.downloadAttachment",
    provider: "google",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "download_attachment",
    description: "Download Gmail attachment body",
    redaction_policy: ["data", "filename", "email"],
    input_schema: z.object({
      messageId: z.string().min(1),
      attachmentId: z.string().min(1),
    }),
  },
  {
    name: "gmail.deleteDraft",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_draft",
    description: "Delete Gmail draft",
    redaction_policy: [],
    input_schema: z.object({ draftId: z.string().min(1) }),
  },
  {
    name: "gmail.listFilters",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_filters",
    description: "List Gmail filters",
    redaction_policy: ["query", "email"],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.createFilter",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_filter",
    description: "Create Gmail filter",
    redaction_policy: ["query", "email", "forward"],
    input_schema: z.object({
      criteria: gmailFilterCriteriaSchema,
      action: gmailFilterActionSchema,
    }),
  },
  {
    name: "gmail.deleteFilter",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_filter",
    description: "Delete Gmail filter",
    redaction_policy: [],
    input_schema: z.object({ filterId: z.string().min(1) }),
  },
  {
    name: "gmail.listSendAsAliases",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_send_as_aliases",
    description: "List Gmail send-as aliases",
    redaction_policy: ["email"],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.getVacation",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_vacation",
    description: "Get Gmail vacation responder settings",
    redaction_policy: ["responseBodyPlainText", "responseBodyHtml"],
    input_schema: z.object({ _reserved: z.never().optional() }),
  },
  {
    name: "gmail.updateVacation",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_vacation",
    description: "Update Gmail vacation responder settings",
    redaction_policy: ["responseBodyPlainText", "responseBodyHtml"],
    input_schema: gmailVacationSettingsSchema,
  },
  {
    name: "gmail.removeLabel",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_label",
    description: "Remove label from Gmail thread",
    redaction_policy: ["label"],
    input_schema: z.object({ threadId: z.string().min(1), label: z.string().min(1) }),
  },
  {
    name: "gmail.getLabel",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_label",
    description: "Get Gmail label details",
    redaction_policy: ["label", "name"],
    input_schema: z.object({ labelId: z.string().min(1) }),
  },
  {
    name: "gmail.updateLabel",
    provider: "google",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "update_label",
    description: "Update Gmail label details",
    redaction_policy: ["label", "name"],
    input_schema: gmailUpdateLabelSchema,
  },
  {
    name: "gmail.deleteLabel",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_label",
    description: "Delete Gmail label",
    redaction_policy: ["label", "name"],
    input_schema: z.object({ labelId: z.string().min(1) }),
  },
  {
    name: "gmail.getFilter",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_filter",
    description: "Get Gmail filter details",
    redaction_policy: ["query", "email", "forward"],
    input_schema: z.object({ filterId: z.string().min(1) }),
  },
  {
    name: "gmail.getSendAsAlias",
    provider: "google",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_send_as_alias",
    description: "Get Gmail send-as alias details",
    redaction_policy: ["email", "signature"],
    input_schema: z.object({ sendAsEmail: emailSchema }),
  },
  {
    name: "gmail.updateSendAsAlias",
    provider: "google",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_send_as_alias",
    description: "Update Gmail send-as alias",
    redaction_policy: ["email", "signature"],
    input_schema: gmailUpdateSendAsAliasSchema,
  },
];
