import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const keppoInternalTools: ToolDefinition[] = [
  {
    name: "keppo.wait_for_action",
    provider: "keppo",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "wait_for_action",
    description: "Long poll action status",
    redaction_policy: [],
    input_schema: z.object({ action_id: z.string().min(1) }),
  },
  {
    name: "keppo.wait_for_actions",
    provider: "keppo",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "wait_for_actions",
    description: "Long poll many action statuses",
    redaction_policy: [],
    input_schema: z.object({ action_ids: z.array(z.string().min(1)).min(1).max(20) }),
  },
  {
    name: "keppo.get_action",
    provider: "keppo",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_action",
    description: "Get one action status",
    redaction_policy: [],
    input_schema: z.object({ action_id: z.string().min(1) }),
  },
  {
    name: "keppo.list_pending_actions",
    provider: "keppo",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_pending_actions",
    description: "List all pending actions",
    redaction_policy: [],
    input_schema: z.object({}),
  },
  {
    name: "keppo.request_more_access",
    provider: "keppo",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "request_more_access",
    description: "Request additional tools or integrations",
    redaction_policy: ["reason"],
    input_schema: z.object({
      reason: z.string().min(1),
      requested_tools: z.array(z.string().min(1)).min(1),
    }),
  },
];
