import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const notionTools: ToolDefinition[] = [
  {
    name: "notion.searchPages",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_pages",
    description: "Search Notion pages",
    redaction_policy: [],
    input_schema: z.object({ query: z.string().default("") }),
  },
  {
    name: "notion.getPage",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_page",
    description: "Get Notion page details",
    redaction_policy: ["content"],
    input_schema: z.object({
      pageId: z.string().min(1),
    }),
  },
  {
    name: "notion.getPageAsMarkdown",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_page_as_markdown",
    description: "Get Notion page content as Markdown",
    redaction_policy: ["content"],
    input_schema: z.object({
      pageId: z.string().min(1),
    }),
  },
  {
    name: "notion.queryDatabase",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "query_database",
    description: "Query Notion database entries",
    redaction_policy: ["content"],
    input_schema: z.object({
      databaseId: z.string().min(1),
      query: z.string().default(""),
      pageSize: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "notion.getDatabase",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_database",
    description: "Get Notion database schema",
    redaction_policy: [],
    input_schema: z.object({
      databaseId: z.string().min(1),
    }),
  },
  {
    name: "notion.getBlockChildren",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_block_children",
    description: "Get Notion block children",
    redaction_policy: ["content"],
    input_schema: z.object({
      blockId: z.string().min(1),
      pageSize: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "notion.getBlock",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_block",
    description: "Get a Notion block",
    redaction_policy: ["content"],
    input_schema: z.object({
      blockId: z.string().min(1),
    }),
  },
  {
    name: "notion.listComments",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_comments",
    description: "List Notion comments",
    redaction_policy: ["content"],
    input_schema: z.object({
      pageId: z.string().min(1),
      pageSize: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "notion.getComment",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_comment",
    description: "Get a Notion comment",
    redaction_policy: ["content"],
    input_schema: z.object({
      commentId: z.string().min(1),
    }),
  },
  {
    name: "notion.getPageProperty",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_page_property",
    description: "Get a Notion page property value",
    redaction_policy: [],
    input_schema: z.object({
      pageId: z.string().min(1),
      propertyId: z.string().min(1),
    }),
  },
  {
    name: "notion.listUsers",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_users",
    description: "List Notion users",
    redaction_policy: [],
    input_schema: z.object({
      pageSize: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "notion.getUser",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user",
    description: "Get a Notion user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
    }),
  },
  {
    name: "notion.getBotUser",
    provider: "notion",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_bot_user",
    description: "Get the Notion bot user",
    redaction_policy: [],
    input_schema: z.object({}),
  },
  {
    name: "notion.createPage",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_page",
    description: "Create Notion page",
    redaction_policy: ["content"],
    input_schema: z.object({
      title: z.string().min(1),
      content: z.string().min(1),
    }),
  },
  {
    name: "notion.createDatabase",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_database",
    description: "Create Notion database",
    redaction_policy: ["title"],
    input_schema: z.object({
      title: z.string().min(1),
      parentPageId: z.string().min(1).optional(),
      propertyNames: z.array(z.string().min(1)).max(50).default([]),
    }),
  },
  {
    name: "notion.updatePage",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_page",
    description: "Update Notion page properties",
    redaction_policy: ["content", "title"],
    input_schema: z
      .object({
        pageId: z.string().min(1),
        title: z.string().min(1).optional(),
        archived: z.boolean().optional(),
      })
      .refine((value) => value.title !== undefined || value.archived !== undefined, {
        message: "At least one of title or archived must be provided.",
      }),
  },
  {
    name: "notion.movePage",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "move_page",
    description: "Move a Notion page to a new parent page",
    redaction_policy: [],
    input_schema: z.object({
      pageId: z.string().min(1),
      parentPageId: z.string().min(1),
    }),
  },
  {
    name: "notion.updatePageMarkdown",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_page_markdown",
    description: "Update Notion page content using Markdown",
    redaction_policy: ["content"],
    input_schema: z.object({
      pageId: z.string().min(1),
      markdown: z.string().trim().min(1),
    }),
  },
  {
    name: "notion.updateDatabase",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_database",
    description: "Update Notion database properties",
    redaction_policy: ["title"],
    input_schema: z
      .object({
        databaseId: z.string().min(1),
        title: z.string().min(1).optional(),
        propertyNames: z.array(z.string().min(1)).max(50).optional(),
      })
      .refine((value) => value.title !== undefined || value.propertyNames !== undefined, {
        message: "At least one of title or propertyNames must be provided.",
      }),
  },
  {
    name: "notion.appendBlockChildren",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "append_block_children",
    description: "Append content blocks to a Notion block",
    redaction_policy: ["content"],
    input_schema: z.object({
      blockId: z.string().min(1),
      content: z.string().min(1),
    }),
  },
  {
    name: "notion.updateBlock",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_block",
    description: "Update Notion block content",
    redaction_policy: ["content"],
    input_schema: z.object({
      blockId: z.string().min(1),
      content: z.string().min(1),
    }),
  },
  {
    name: "notion.deleteBlock",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_block",
    description: "Delete a Notion block",
    redaction_policy: [],
    input_schema: z.object({
      blockId: z.string().min(1),
    }),
  },
  {
    name: "notion.createComment",
    provider: "notion",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_comment",
    description: "Create Notion page comment",
    redaction_policy: ["content"],
    input_schema: z.object({
      pageId: z.string().min(1),
      content: z.string().min(1),
    }),
  },
];
