import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const redditTools: ToolDefinition[] = [
  {
    name: "reddit.searchPosts",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_posts",
    description: "Search Reddit posts",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().default("all"),
      query: z.string().default(""),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.createPost",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_post",
    description: "Create Reddit post",
    redaction_policy: ["body"],
    input_schema: z.object({
      subreddit: z.string().min(1),
      title: z.string().min(1),
      body: z.string().min(1),
    }),
  },
  {
    name: "reddit.createComment",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_comment",
    description: "Reply to a Reddit post or comment",
    redaction_policy: ["body"],
    input_schema: z.object({
      parentId: z.string().min(1),
      body: z.string().min(1),
    }),
  },
  {
    name: "reddit.getPostComments",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_post_comments",
    description: "Get Reddit post and comment tree",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      postId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getInfo",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_info",
    description: "Bulk lookup Reddit things by fullname IDs",
    redaction_policy: [],
    input_schema: z.object({
      thingIds: z.array(z.string().min(1)).min(1).max(25),
    }),
  },
  {
    name: "reddit.listHot",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_hot",
    description: "List hot posts from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listNew",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_new",
    description: "List new posts from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listTop",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_top",
    description: "List top posts from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listRising",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_rising",
    description: "List rising posts from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listControversial",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_controversial",
    description: "List controversial posts from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.searchSubreddits",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_subreddits",
    description: "Search Reddit communities",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getUserOverview",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_overview",
    description: "Get a Reddit user's overview feed",
    redaction_policy: [],
    input_schema: z.object({
      username: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getUserAbout",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_about",
    description: "Get Reddit user profile details",
    redaction_policy: [],
    input_schema: z.object({
      username: z.string().min(1),
    }),
  },
  {
    name: "reddit.vote",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "vote",
    description: "Vote on a Reddit post or comment",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
      direction: z.union([z.literal(-1), z.literal(0), z.literal(1)]),
    }),
  },
  {
    name: "reddit.composeMessage",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "compose_message",
    description: "Send a Reddit private message",
    redaction_policy: ["body", "subject"],
    input_schema: z.object({
      to: z.string().min(1),
      subject: z.string().min(1),
      body: z.string().min(1),
    }),
  },
  {
    name: "reddit.editPost",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "edit_post",
    description: "Edit a Reddit post or comment body",
    redaction_policy: ["body"],
    input_schema: z.object({
      thingId: z.string().min(1),
      body: z.string().min(1),
    }),
  },
  {
    name: "reddit.deletePost",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_post",
    description: "Delete a Reddit post or comment",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.approve",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "approve",
    description: "Approve a Reddit post or comment in moderation queue",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.removeContent",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_content",
    description: "Remove a Reddit post or comment via moderation action",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.distinguish",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "distinguish",
    description: "Distinguish Reddit content as moderator",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
      sticky: z.boolean().optional(),
    }),
  },
  {
    name: "reddit.lockPost",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "lock_post",
    description: "Lock a Reddit post to prevent new comments",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.unlockPost",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unlock_post",
    description: "Unlock a Reddit post to allow comments again",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.stickyPost",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "sticky_post",
    description: "Sticky or unsticky a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
      state: z.boolean().optional(),
      slot: z.union([z.literal(1), z.literal(2)]).optional(),
    }),
  },
  {
    name: "reddit.getModQueue",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_mod_queue",
    description: "List moderation queue items",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getReports",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_reports",
    description: "List reported Reddit items",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getModLog",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_mod_log",
    description: "List subreddit moderation log entries",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getSubredditRules",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_subreddit_rules",
    description: "List subreddit rules",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
    }),
  },
  {
    name: "reddit.markNsfw",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "mark_nsfw",
    description: "Mark a Reddit post as NSFW",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.unmarkNsfw",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unmark_nsfw",
    description: "Remove NSFW flag from a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.spoiler",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "spoiler",
    description: "Mark a Reddit post as spoiler",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.unspoiler",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unspoiler",
    description: "Remove spoiler tag from a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.selectFlair",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "select_flair",
    description: "Apply subreddit flair to a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      thingId: z.string().min(1),
      text: z.string().min(1),
      cssClass: z.string().min(1).optional(),
    }),
  },
  {
    name: "reddit.subscribe",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "subscribe",
    description: "Subscribe or unsubscribe from a subreddit",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
      action: z.union([z.literal("sub"), z.literal("unsub")]),
    }),
  },
  {
    name: "reddit.savePost",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "save_post",
    description: "Save a Reddit post or comment",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.unsavePost",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unsave_post",
    description: "Remove saved state from a Reddit post or comment",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.hidePost",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "hide_post",
    description: "Hide a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.unhidePost",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unhide_post",
    description: "Unhide a Reddit post",
    redaction_policy: [],
    input_schema: z.object({
      thingId: z.string().min(1),
    }),
  },
  {
    name: "reddit.reportContent",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "report_content",
    description: "Report Reddit content for policy violations",
    redaction_policy: ["reason"],
    input_schema: z.object({
      thingId: z.string().min(1),
      reason: z.string().min(1),
    }),
  },
  {
    name: "reddit.readMessage",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "read_message",
    description: "Mark a Reddit message as read",
    redaction_policy: [],
    input_schema: z.object({
      messageId: z.string().min(1),
    }),
  },
  {
    name: "reddit.readAllMessages",
    provider: "reddit",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "read_all_messages",
    description: "Mark all Reddit inbox messages as read",
    redaction_policy: [],
    input_schema: z.object({}),
  },
  {
    name: "reddit.listInbox",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_inbox",
    description: "List Reddit inbox messages",
    redaction_policy: [],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listUnreadMessages",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_unread_messages",
    description: "List unread Reddit inbox messages",
    redaction_policy: [],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listSentMessages",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_sent_messages",
    description: "List sent Reddit messages",
    redaction_policy: [],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.listMentions",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_mentions",
    description: "List Reddit username mention messages",
    redaction_policy: [],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getSubredditInfo",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_subreddit_info",
    description: "Get subreddit metadata",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().min(1),
    }),
  },
  {
    name: "reddit.listModmail",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_modmail",
    description: "List Reddit modmail conversations",
    redaction_policy: [],
    input_schema: z.object({
      subreddit: z.string().default("all"),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "reddit.getModmail",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_modmail",
    description: "Get a Reddit modmail conversation",
    redaction_policy: [],
    input_schema: z.object({
      conversationId: z.string().min(1),
    }),
  },
  {
    name: "reddit.replyModmail",
    provider: "reddit",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "reply_modmail",
    description: "Reply to a Reddit modmail conversation",
    redaction_policy: ["body"],
    input_schema: z.object({
      conversationId: z.string().min(1),
      body: z.string().min(1),
      isInternal: z.boolean().optional(),
    }),
  },
  {
    name: "reddit.getMe",
    provider: "reddit",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_me",
    description: "Get authenticated Reddit user",
    redaction_policy: [],
    input_schema: z.object({}),
  },
];
