import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const slackTools: ToolDefinition[] = [
  {
    name: "slack.listChannels",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_channels",
    description: "List Slack channels",
    redaction_policy: ["email"],
    input_schema: z.object({}),
  },
  {
    name: "slack.getChannelHistory",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_channel_history",
    description: "Get recent Slack channel message history",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      limit: z.number().int().min(1).max(200).default(50),
    }),
  },
  {
    name: "slack.getThreadReplies",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_thread_replies",
    description: "Get Slack thread replies for a message",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      threadTs: z.string().min(1),
      limit: z.number().int().min(1).max(200).default(50),
    }),
  },
  {
    name: "slack.getReactions",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_reactions",
    description: "Get reactions on a Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.listUsers",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_users",
    description: "List Slack workspace users",
    redaction_policy: ["email"],
    input_schema: z.object({
      limit: z.number().int().min(1).max(200).default(200),
    }),
  },
  {
    name: "slack.getUserInfo",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_info",
    description: "Get Slack user details",
    redaction_policy: ["email"],
    input_schema: z.object({
      userId: z.string().min(1),
    }),
  },
  {
    name: "slack.getChannelInfo",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_channel_info",
    description: "Get Slack channel details",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.searchMessages",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_messages",
    description: "Search Slack messages",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "slack.postMessage",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "post_message",
    description: "Post Slack message",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      text: z.string().min(1),
    }),
  },
  {
    name: "slack.updateMessage",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_message",
    description: "Update Slack message",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
      text: z.string().min(1),
    }),
  },
  {
    name: "slack.deleteMessage",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_message",
    description: "Delete Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.addReaction",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_reaction",
    description: "Add reaction to Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
      name: z.string().min(1),
    }),
  },
  {
    name: "slack.postEphemeral",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "post_ephemeral",
    description: "Post ephemeral Slack message",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      userId: z.string().min(1),
      text: z.string().min(1),
    }),
  },
  {
    name: "slack.uploadFile",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "upload_file",
    description: "Upload file to Slack channel",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      filename: z.string().min(1),
      content: z.string().min(1),
      title: z.string().min(1).optional(),
    }),
  },
  {
    name: "slack.createChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_channel",
    description: "Create Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      name: z.string().min(1),
      isPrivate: z.boolean().optional(),
    }),
  },
  {
    name: "slack.inviteToChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "invite_to_channel",
    description: "Invite users to Slack channel",
    redaction_policy: ["email"],
    input_schema: z.object({
      channel: z.string().min(1),
      userIds: z.array(z.string().min(1)).min(1).max(50),
    }),
  },
  {
    name: "slack.joinChannel",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "join_channel",
    description: "Join Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.listChannelMembers",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_channel_members",
    description: "List Slack channel members",
    redaction_policy: ["email"],
    input_schema: z.object({
      channel: z.string().min(1),
      limit: z.number().int().min(1).max(1000).default(200),
    }),
  },
  {
    name: "slack.markChannelRead",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "mark_channel_read",
    description: "Mark Slack channel read up to timestamp",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.archiveChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "archive_channel",
    description: "Archive Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.unarchiveChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unarchive_channel",
    description: "Unarchive Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.setChannelPurpose",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "set_channel_purpose",
    description: "Set Slack channel purpose",
    redaction_policy: ["text"],
    input_schema: z.object({
      channel: z.string().min(1),
      purpose: z.string().min(1).max(250),
    }),
  },
  {
    name: "slack.setChannelTopic",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "set_channel_topic",
    description: "Set Slack channel topic",
    redaction_policy: ["text"],
    input_schema: z.object({
      channel: z.string().min(1),
      topic: z.string().min(1).max(250),
    }),
  },
  {
    name: "slack.openDM",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "open_dm",
    description: "Open Slack DM conversation",
    redaction_policy: ["email"],
    input_schema: z.object({
      userIds: z.array(z.string().min(1)).min(1).max(8),
    }),
  },
  {
    name: "slack.renameChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "rename_channel",
    description: "Rename Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      name: z.string().min(1).max(80),
    }),
  },
  {
    name: "slack.kickFromChannel",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "kick_from_channel",
    description: "Remove user from Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      userId: z.string().min(1),
    }),
  },
  {
    name: "slack.leaveChannel",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "leave_channel",
    description: "Leave Slack channel",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.closeDM",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "close_dm",
    description: "Close Slack DM conversation",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.addBookmark",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_bookmark",
    description: "Add Slack channel bookmark",
    redaction_policy: ["url", "text"],
    input_schema: z.object({
      channel: z.string().min(1),
      title: z.string().min(1),
      link: z.string().url(),
      emoji: z.string().min(1).optional(),
    }),
  },
  {
    name: "slack.editBookmark",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "edit_bookmark",
    description: "Edit Slack channel bookmark",
    redaction_policy: ["url", "text"],
    input_schema: z
      .object({
        channel: z.string().min(1),
        bookmarkId: z.string().min(1),
        title: z.string().min(1).optional(),
        link: z.string().url().optional(),
        emoji: z.string().min(1).optional(),
      })
      .refine(
        (value) =>
          typeof value.title === "string" ||
          typeof value.link === "string" ||
          typeof value.emoji === "string",
        { message: "At least one bookmark field must be provided." },
      ),
  },
  {
    name: "slack.removeBookmark",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_bookmark",
    description: "Remove Slack channel bookmark",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      bookmarkId: z.string().min(1),
    }),
  },
  {
    name: "slack.listBookmarks",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_bookmarks",
    description: "List Slack channel bookmarks",
    redaction_policy: ["url", "text"],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.addReminder",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_reminder",
    description: "Create Slack reminder",
    redaction_policy: ["text"],
    input_schema: z.object({
      text: z.string().min(1),
      time: z.number().int().positive(),
      userId: z.string().min(1).optional(),
    }),
  },
  {
    name: "slack.listReminders",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_reminders",
    description: "List Slack reminders",
    redaction_policy: ["text"],
    input_schema: z.object({
      userId: z.string().min(1).optional(),
      _reserved: z.never().optional(),
    }),
  },
  {
    name: "slack.deleteReminder",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_reminder",
    description: "Delete Slack reminder",
    redaction_policy: [],
    input_schema: z.object({
      reminderId: z.string().min(1),
    }),
  },
  {
    name: "slack.listUserGroups",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_user_groups",
    description: "List Slack user groups",
    redaction_policy: [],
    input_schema: z.object({
      includeDisabled: z.boolean().optional(),
      _reserved: z.never().optional(),
    }),
  },
  {
    name: "slack.listUserGroupMembers",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_user_group_members",
    description: "List Slack user group members",
    redaction_policy: ["email"],
    input_schema: z.object({
      userGroupId: z.string().min(1),
      includeDisabled: z.boolean().optional(),
    }),
  },
  {
    name: "slack.getUserPresence",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_presence",
    description: "Get Slack user presence",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
    }),
  },
  {
    name: "slack.listReactions",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_reactions",
    description: "List Slack reactions",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(200).default(20),
    }),
  },
  {
    name: "slack.meMessage",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "me_message",
    description: "Send Slack /me message",
    redaction_policy: ["text"],
    input_schema: z.object({
      channel: z.string().min(1),
      text: z.string().min(1),
    }),
  },
  {
    name: "slack.scheduleMessage",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "schedule_message",
    description: "Schedule Slack message",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
      text: z.string().min(1),
      postAt: z.number().int().positive(),
    }),
  },
  {
    name: "slack.deleteScheduledMessage",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_scheduled_message",
    description: "Delete scheduled Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      scheduledMessageId: z.string().min(1),
    }),
  },
  {
    name: "slack.listScheduledMessages",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_scheduled_messages",
    description: "List Slack scheduled messages",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "slack.getPermalink",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_permalink",
    description: "Get Slack message permalink",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.removeReaction",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_reaction",
    description: "Remove reaction from Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
      name: z.string().min(1),
    }),
  },
  {
    name: "slack.pinMessage",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "pin_message",
    description: "Pin Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.unpinMessage",
    provider: "slack",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unpin_message",
    description: "Unpin Slack message",
    redaction_policy: [],
    input_schema: z.object({
      channel: z.string().min(1),
      ts: z.string().min(1),
    }),
  },
  {
    name: "slack.listPins",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_pins",
    description: "List Slack channel pins",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1),
    }),
  },
  {
    name: "slack.listFiles",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "list_files",
    description: "List Slack files",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      channel: z.string().min(1).optional(),
      userId: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(200).default(20),
    }),
  },
  {
    name: "slack.getFileInfo",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_file_info",
    description: "Get Slack file info",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      fileId: z.string().min(1),
    }),
  },
  {
    name: "slack.deleteFile",
    provider: "slack",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_file",
    description: "Delete Slack file",
    redaction_policy: [],
    input_schema: z.object({
      fileId: z.string().min(1),
    }),
  },
  {
    name: "slack.getUserProfile",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_profile",
    description: "Get Slack user profile",
    redaction_policy: ["email", "text"],
    input_schema: z.object({
      userId: z.string().min(1),
    }),
  },
  {
    name: "slack.searchFiles",
    provider: "slack",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_files",
    description: "Search Slack files",
    redaction_policy: ["text", "email"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
];
