import { z } from "zod";
import type { ToolDefinition } from "./types.js";

const emailSchema = z.string().email();

export const stripeTools: ToolDefinition[] = [
  {
    name: "stripe.lookupCustomer",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "lookup_customer",
    description: "Lookup Stripe customer",
    redaction_policy: ["email", "address", "card"],
    input_schema: z.object({ customerId: z.string().min(1) }),
  },
  {
    name: "stripe.listSubscriptions",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_subscriptions",
    description: "List Stripe subscriptions",
    redaction_policy: ["email", "address"],
    input_schema: z.object({ customerId: z.string().min(1) }),
  },
  {
    name: "stripe.listCharges",
    provider: "stripe",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_charges",
    description: "List Stripe charges",
    redaction_policy: ["email", "address"],
    input_schema: z.object({ customerId: z.string().min(1) }),
  },
  {
    name: "stripe.invoiceHistory",
    provider: "stripe",
    capability: "read",
    risk_level: "medium",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "invoice_history",
    description: "Get Stripe invoice history",
    redaction_policy: ["email", "address"],
    input_schema: z.object({ customerId: z.string().min(1) }),
  },
  {
    name: "stripe.issueRefund",
    provider: "stripe",
    capability: "write",
    risk_level: "critical",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "refund",
    description: "Issue a Stripe refund",
    redaction_policy: ["amount", "currency", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      chargeId: z.string().min(1),
      amount: z.number().positive(),
      currency: z.string().length(3),
    }),
  },
  {
    name: "stripe.cancelSubscription",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "cancel_subscription",
    description: "Cancel a Stripe subscription",
    redaction_policy: ["email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
      atPeriodEnd: z.boolean().default(true),
    }),
  },
  {
    name: "stripe.adjustBalance",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "adjust_credits",
    description: "Adjust customer balance",
    redaction_policy: ["amount", "email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      amount: z.number(),
      currency: z.string().length(3),
      reason: z.string().min(1),
    }),
  },
  {
    name: "stripe.searchCustomers",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "search_customers",
    description: "Search Stripe customers",
    redaction_policy: ["email", "address", "card"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.updateCustomer",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_customer",
    description: "Update Stripe customer details",
    redaction_policy: ["email", "address", "phone", "name"],
    input_schema: z
      .object({
        customerId: z.string().min(1),
        email: emailSchema.optional(),
        name: z.string().min(1).optional(),
        phone: z.string().min(1).optional(),
        metadata: z.record(z.string(), z.string()).optional(),
      })
      .refine(
        (value) =>
          typeof value.email === "string" ||
          typeof value.name === "string" ||
          typeof value.phone === "string" ||
          !!value.metadata,
        {
          message: "At least one customer field must be updated.",
        },
      ),
  },
  {
    name: "stripe.getSubscription",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_subscription",
    description: "Get Stripe subscription details",
    redaction_policy: ["email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
    }),
  },
  {
    name: "stripe.updateSubscription",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_subscription",
    description: "Update Stripe subscription",
    redaction_policy: ["email"],
    input_schema: z
      .object({
        customerId: z.string().min(1),
        subscriptionId: z.string().min(1),
        priceId: z.string().min(1).optional(),
        quantity: z.number().int().positive().optional(),
        cancelAtPeriodEnd: z.boolean().optional(),
      })
      .refine(
        (value) =>
          typeof value.priceId === "string" ||
          typeof value.quantity === "number" ||
          typeof value.cancelAtPeriodEnd === "boolean",
        {
          message: "At least one subscription field must be updated.",
        },
      ),
  },
  {
    name: "stripe.resumeSubscription",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "resume_subscription",
    description: "Resume a paused Stripe subscription",
    redaction_policy: ["email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
    }),
  },
  {
    name: "stripe.getInvoice",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_invoice",
    description: "Get Stripe invoice details",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.previewInvoice",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "preview_invoice",
    description: "Preview upcoming Stripe invoice",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1).optional(),
      priceId: z.string().min(1).optional(),
      quantity: z.number().int().positive().optional(),
    }),
  },
  {
    name: "stripe.sendInvoice",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "send_invoice",
    description: "Send Stripe invoice email",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.voidInvoice",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "void_invoice",
    description: "Void Stripe invoice",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.payInvoice",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "pay_invoice",
    description: "Pay Stripe invoice",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listPaymentMethods",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_payment_methods",
    description: "List Stripe payment methods",
    redaction_policy: ["card", "email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      type: z.enum(["card", "us_bank_account"]).default("card"),
    }),
  },
  {
    name: "stripe.getRefund",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_refund",
    description: "Get Stripe refund details",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      refundId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listRefunds",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_refunds",
    description: "List Stripe refunds",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getCharge",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_charge",
    description: "Get Stripe charge details",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      chargeId: z.string().min(1),
    }),
  },
  {
    name: "stripe.createCreditNote",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_credit_note",
    description: "Create Stripe credit note",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
      amount: z.number().positive(),
      reason: z.string().min(1).optional(),
    }),
  },
  {
    name: "stripe.listCreditNotes",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_credit_notes",
    description: "List Stripe credit notes",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getDispute",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_dispute",
    description: "Get Stripe dispute details",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      disputeId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listDisputes",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_disputes",
    description: "List Stripe disputes",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.updateDispute",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_dispute",
    description: "Update Stripe dispute evidence",
    redaction_policy: ["body", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      disputeId: z.string().min(1),
      evidenceSummary: z.string().min(1),
    }),
  },
  {
    name: "stripe.closeDispute",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "close_dispute",
    description: "Close Stripe dispute",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      disputeId: z.string().min(1),
    }),
  },
  {
    name: "stripe.createPortalSession",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_portal_session",
    description: "Create Stripe billing portal session",
    redaction_policy: ["url", "email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      returnUrl: z.string().url(),
    }),
  },
  {
    name: "stripe.listBalanceTransactions",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_balance_transactions",
    description: "List Stripe customer balance transactions",
    redaction_policy: ["amount", "email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.searchCharges",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "search_charges",
    description: "Search Stripe charges",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.searchSubscriptions",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "search_subscriptions",
    description: "Search Stripe subscriptions",
    redaction_policy: ["email"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.searchInvoices",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "search_invoices",
    description: "Search Stripe invoices",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getPaymentIntent",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_payment_intent",
    description: "Get Stripe payment intent details",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      paymentIntentId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listPaymentIntents",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_payment_intents",
    description: "List Stripe payment intents",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.searchPaymentIntents",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "search_payment_intents",
    description: "Search Stripe payment intents",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.detachPaymentMethod",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "detach_payment_method",
    description: "Detach Stripe payment method",
    redaction_policy: ["card", "email"],
    input_schema: z.object({
      customerId: z.string().min(1),
      paymentMethodId: z.string().min(1),
    }),
  },
  {
    name: "stripe.cancelRefund",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "cancel_refund",
    description: "Cancel pending Stripe refund",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      refundId: z.string().min(1),
    }),
  },
  {
    name: "stripe.getCoupon",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_coupon",
    description: "Get Stripe coupon details",
    redaction_policy: [],
    input_schema: z.object({
      couponId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listCoupons",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_coupons",
    description: "List Stripe coupons",
    redaction_policy: [],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getPromotionCode",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_promotion_code",
    description: "Get Stripe promotion code details",
    redaction_policy: [],
    input_schema: z.object({
      promotionCodeId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listPromotionCodes",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_promotion_codes",
    description: "List Stripe promotion codes",
    redaction_policy: [],
    input_schema: z.object({
      code: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.createInvoiceItem",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_invoice_item",
    description: "Create Stripe invoice item",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      amount: z.number(),
      currency: z.string().length(3),
      description: z.string().min(1).optional(),
      invoiceId: z.string().min(1).optional(),
    }),
  },
  {
    name: "stripe.deleteInvoiceItem",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_invoice_item",
    description: "Delete Stripe invoice item",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceItemId: z.string().min(1),
    }),
  },
  {
    name: "stripe.getProduct",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_product",
    description: "Get Stripe product details",
    redaction_policy: [],
    input_schema: z.object({
      productId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listProducts",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_products",
    description: "List Stripe products",
    redaction_policy: [],
    input_schema: z.object({
      active: z.boolean().optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getPrice",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_price",
    description: "Get Stripe price details",
    redaction_policy: [],
    input_schema: z.object({
      priceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listPrices",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_prices",
    description: "List Stripe prices",
    redaction_policy: [],
    input_schema: z.object({
      productId: z.string().min(1).optional(),
      active: z.boolean().optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getBalanceTransaction",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_balance_transaction",
    description: "Get Stripe balance transaction details",
    redaction_policy: ["amount"],
    input_schema: z.object({
      balanceTransactionId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listGlobalBalanceTransactions",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_global_balance_transactions",
    description: "List Stripe balance transactions",
    redaction_policy: ["amount"],
    input_schema: z.object({
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getCreditNote",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_credit_note",
    description: "Get Stripe credit note details",
    redaction_policy: ["amount"],
    input_schema: z.object({
      creditNoteId: z.string().min(1),
    }),
  },
  {
    name: "stripe.previewCreditNote",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "preview_credit_note",
    description: "Preview Stripe credit note",
    redaction_policy: ["amount"],
    input_schema: z.object({
      invoiceId: z.string().min(1),
      amount: z.number().int().positive(),
      reason: z.string().min(1).optional(),
    }),
  },
  {
    name: "stripe.updateRefund",
    provider: "stripe",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_refund",
    description: "Update Stripe refund metadata",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      refundId: z.string().min(1),
      metadata: z.record(z.string(), z.string()).refine((value) => Object.keys(value).length > 0, {
        message: "metadata must include at least one key",
      }),
    }),
  },
  {
    name: "stripe.voidCreditNote",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "void_credit_note",
    description: "Void Stripe credit note",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      creditNoteId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listSubscriptionItems",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_subscription_items",
    description: "List Stripe subscription items",
    redaction_policy: ["amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.createSubscriptionItem",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_subscription_item",
    description: "Create Stripe subscription item",
    redaction_policy: ["amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
      priceId: z.string().min(1),
      quantity: z.number().int().min(1).max(1000).optional(),
    }),
  },
  {
    name: "stripe.updateSubscriptionItem",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_subscription_item",
    description: "Update Stripe subscription item",
    redaction_policy: ["amount"],
    input_schema: z
      .object({
        customerId: z.string().min(1),
        subscriptionItemId: z.string().min(1),
        quantity: z.number().int().min(1).max(1000).optional(),
        priceId: z.string().min(1).optional(),
      })
      .refine((value) => typeof value.quantity === "number" || typeof value.priceId === "string", {
        message: "quantity or priceId is required",
      }),
  },
  {
    name: "stripe.deleteSubscriptionItem",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_subscription_item",
    description: "Delete Stripe subscription item",
    redaction_policy: ["amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionItemId: z.string().min(1),
    }),
  },
  {
    name: "stripe.getSubscriptionSchedule",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_subscription_schedule",
    description: "Get Stripe subscription schedule details",
    redaction_policy: [],
    input_schema: z.object({
      subscriptionScheduleId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listSubscriptionSchedules",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_subscription_schedules",
    description: "List Stripe subscription schedules",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.updateSubscriptionSchedule",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_subscription_schedule",
    description: "Update Stripe subscription schedule",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionScheduleId: z.string().min(1),
      endBehavior: z.enum(["release", "cancel", "none"]).optional(),
    }),
  },
  {
    name: "stripe.cancelSubscriptionSchedule",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "cancel_subscription_schedule",
    description: "Cancel Stripe subscription schedule",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionScheduleId: z.string().min(1),
    }),
  },
  {
    name: "stripe.listCustomerTaxIds",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_customer_tax_ids",
    description: "List Stripe customer tax IDs",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.createCustomerTaxId",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_customer_tax_id",
    description: "Create Stripe customer tax ID",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1),
      type: z.string().min(1),
      value: z.string().min(1),
    }),
  },
  {
    name: "stripe.deleteCustomerTaxId",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_customer_tax_id",
    description: "Delete Stripe customer tax ID",
    redaction_policy: [],
    input_schema: z.object({
      customerId: z.string().min(1),
      taxId: z.string().min(1),
    }),
  },
  {
    name: "stripe.createCoupon",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_coupon",
    description: "Create Stripe coupon",
    redaction_policy: ["amount"],
    input_schema: z
      .object({
        id: z.string().min(1).optional(),
        name: z.string().min(1).optional(),
        percentOff: z.number().positive().max(100).optional(),
        amountOff: z.number().int().positive().optional(),
        currency: z.string().length(3).optional(),
        duration: z.enum(["once", "repeating", "forever"]).optional(),
        durationInMonths: z.number().int().min(1).max(36).optional(),
        maxRedemptions: z.number().int().min(1).optional(),
      })
      .refine(
        (value) => typeof value.percentOff === "number" || typeof value.amountOff === "number",
        {
          message: "percentOff or amountOff is required",
        },
      ),
  },
  {
    name: "stripe.createPromotionCode",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_promotion_code",
    description: "Create Stripe promotion code",
    redaction_policy: [],
    input_schema: z.object({
      couponId: z.string().min(1),
      code: z.string().min(1).optional(),
      maxRedemptions: z.number().int().min(1).optional(),
    }),
  },
  {
    name: "stripe.getCheckoutSession",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_checkout_session",
    description: "Get Stripe checkout session details",
    redaction_policy: ["url", "amount"],
    input_schema: z.object({
      checkoutSessionId: z.string().min(1),
    }),
  },
  {
    name: "stripe.createCheckoutSession",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_checkout_session",
    description: "Create Stripe checkout session",
    redaction_policy: ["url", "amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
      successUrl: z.string().url(),
      cancelUrl: z.string().url(),
      mode: z.enum(["payment", "setup", "subscription"]).default("payment"),
      priceId: z.string().min(1).optional(),
      quantity: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "stripe.createSetupIntent",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_setup_intent",
    description: "Create Stripe setup intent",
    redaction_policy: ["card", "url"],
    input_schema: z.object({
      customerId: z.string().min(1),
      paymentMethodType: z.enum(["card", "us_bank_account"]).optional(),
      usage: z.enum(["on_session", "off_session"]).optional(),
    }),
  },
  {
    name: "stripe.listEvents",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "list_events",
    description: "List Stripe events",
    redaction_policy: [],
    input_schema: z.object({
      type: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(100).default(20),
    }),
  },
  {
    name: "stripe.getEvent",
    provider: "stripe",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "high",
    action_type: "get_event",
    description: "Get Stripe event details",
    redaction_policy: [],
    input_schema: z.object({
      eventId: z.string().min(1),
    }),
  },
  {
    name: "stripe.updateCharge",
    provider: "stripe",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "update_charge",
    description: "Update Stripe charge metadata",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z
      .object({
        customerId: z.string().min(1),
        chargeId: z.string().min(1),
        description: z.string().min(1).optional(),
        metadata: z.record(z.string(), z.string()).optional(),
      })
      .refine(
        (value) => typeof value.description === "string" || typeof value.metadata === "object",
        {
          message: "description or metadata is required",
        },
      ),
  },
  {
    name: "stripe.createInvoice",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_invoice",
    description: "Create Stripe invoice",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      autoAdvance: z.boolean().optional(),
      collectionMethod: z.enum(["charge_automatically", "send_invoice"]).optional(),
      daysUntilDue: z.number().int().min(1).max(365).optional(),
      description: z.string().min(1).optional(),
    }),
  },
  {
    name: "stripe.createSubscription",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_subscription",
    description: "Create Stripe subscription",
    redaction_policy: ["amount", "email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      priceId: z.string().min(1),
      quantity: z.number().int().min(1).max(1000).optional(),
      trialPeriodDays: z.number().int().min(1).max(365).optional(),
    }),
  },
  {
    name: "stripe.deleteCustomerDiscount",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_customer_discount",
    description: "Delete Stripe customer discount",
    redaction_policy: ["amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
    }),
  },
  {
    name: "stripe.deleteSubscriptionDiscount",
    provider: "stripe",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "delete_subscription_discount",
    description: "Delete Stripe subscription discount",
    redaction_policy: ["amount"],
    input_schema: z.object({
      customerId: z.string().min(1),
      subscriptionId: z.string().min(1),
    }),
  },
  {
    name: "stripe.finalizeInvoice",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "finalize_invoice",
    description: "Finalize Stripe invoice",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
  {
    name: "stripe.markUncollectible",
    provider: "stripe",
    capability: "write",
    risk_level: "high",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "mark_uncollectible",
    description: "Mark Stripe invoice uncollectible",
    redaction_policy: ["email", "address"],
    input_schema: z.object({
      customerId: z.string().min(1),
      invoiceId: z.string().min(1),
    }),
  },
];
