import { z } from "zod";
import type { ToolDefinition } from "./types.js";

export const xTools: ToolDefinition[] = [
  {
    name: "x.searchPosts",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_posts",
    description: "Search X posts",
    redaction_policy: [],
    input_schema: z.object({ query: z.string().default("") }),
  },
  {
    name: "x.createPost",
    provider: "x",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_post",
    description: "Create X post",
    redaction_policy: ["body"],
    input_schema: z.object({ body: z.string().min(1) }),
  },
  {
    name: "x.deletePost",
    provider: "x",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_post",
    description: "Delete an X post",
    redaction_policy: [],
    input_schema: z.object({
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.getPost",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_post",
    description: "Get a single X post by ID",
    redaction_policy: [],
    input_schema: z.object({
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.getPosts",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_posts",
    description: "Batch lookup X posts by IDs",
    redaction_policy: [],
    input_schema: z.object({
      postIds: z.array(z.string().min(1)).min(1).max(100),
    }),
  },
  {
    name: "x.getUserTimeline",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_timeline",
    description: "List posts from a user's timeline",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getUserMentions",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_mentions",
    description: "List posts mentioning a user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getUserByUsername",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_by_username",
    description: "Get X user by username",
    redaction_policy: [],
    input_schema: z.object({
      username: z.string().min(1),
    }),
  },
  {
    name: "x.getUserById",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_user_by_id",
    description: "Get X user by ID",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
    }),
  },
  {
    name: "x.getMe",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_me",
    description: "Get authenticated X user",
    redaction_policy: [],
    input_schema: z.object({}),
  },
  {
    name: "x.likePost",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "like_post",
    description: "Like an X post",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.unlikePost",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unlike_post",
    description: "Remove like from an X post",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.repost",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "repost",
    description: "Repost an X post",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.undoRepost",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "undo_repost",
    description: "Undo repost of an X post",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.sendDM",
    provider: "x",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "send_dm",
    description: "Send an X direct message",
    redaction_policy: ["text"],
    input_schema: z.object({
      conversationId: z.string().min(1),
      text: z.string().min(1),
    }),
  },
  {
    name: "x.getDMEvents",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_dm_events",
    description: "List X DM events",
    redaction_policy: [],
    input_schema: z.object({
      conversationId: z.string().min(1).optional(),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getQuoteTweets",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_quote_tweets",
    description: "Get quote tweets for an X post",
    redaction_policy: [],
    input_schema: z.object({
      postId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getFollowers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_followers",
    description: "List followers for an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getFollowing",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_following",
    description: "List accounts followed by an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.followUser",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "follow_user",
    description: "Follow an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.unfollowUser",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unfollow_user",
    description: "Unfollow an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.getLikingUsers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_liking_users",
    description: "List users who liked an X post",
    redaction_policy: [],
    input_schema: z.object({
      postId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getLikedPosts",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_liked_posts",
    description: "List posts liked by an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getRepostedBy",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_reposted_by",
    description: "List users who reposted an X post",
    redaction_policy: [],
    input_schema: z.object({
      postId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.blockUser",
    provider: "x",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "block_user",
    description: "Block an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.unblockUser",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unblock_user",
    description: "Unblock an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.getBlockedUsers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_blocked_users",
    description: "List blocked X users",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.muteUser",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "mute_user",
    description: "Mute an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.unmuteUser",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "unmute_user",
    description: "Unmute an X user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      targetUserId: z.string().min(1),
    }),
  },
  {
    name: "x.getMutedUsers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_muted_users",
    description: "List muted X users",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.createBookmark",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_bookmark",
    description: "Bookmark an X post",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.deleteBookmark",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_bookmark",
    description: "Remove an X post bookmark",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      postId: z.string().min(1),
    }),
  },
  {
    name: "x.getBookmarks",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_bookmarks",
    description: "List bookmarked X posts",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.createDMConversation",
    provider: "x",
    capability: "write",
    risk_level: "medium",
    requires_approval: true,
    output_sensitivity: "high",
    action_type: "create_dm_conversation",
    description: "Create an X DM conversation",
    redaction_policy: ["text"],
    input_schema: z.object({
      participantIds: z.array(z.string().min(1)).min(1).max(10),
      text: z.string().min(1).optional(),
    }),
  },
  {
    name: "x.searchUsers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_users",
    description: "Search X users by query",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getUsersByUsernames",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_users_by_usernames",
    description: "Get X users by usernames",
    redaction_policy: [],
    input_schema: z.object({
      usernames: z.array(z.string().min(1)).min(1).max(100),
    }),
  },
  {
    name: "x.createList",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "create_list",
    description: "Create an X list",
    redaction_policy: [],
    input_schema: z.object({
      name: z.string().min(1).max(120),
      description: z.string().max(500).optional(),
      isPrivate: z.boolean().optional(),
    }),
  },
  {
    name: "x.deleteList",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "delete_list",
    description: "Delete an X list",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
    }),
  },
  {
    name: "x.updateList",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "update_list",
    description: "Update X list metadata",
    redaction_policy: [],
    input_schema: z
      .object({
        listId: z.string().min(1),
        name: z.string().min(1).max(120).optional(),
        description: z.string().max(500).optional(),
        isPrivate: z.boolean().optional(),
      })
      .refine(
        (value) =>
          value.name !== undefined ||
          value.description !== undefined ||
          value.isPrivate !== undefined,
        {
          message: "At least one of name, description, or isPrivate must be provided.",
        },
      ),
  },
  {
    name: "x.getList",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_list",
    description: "Get X list metadata",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
    }),
  },
  {
    name: "x.getOwnedLists",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_owned_lists",
    description: "List X lists owned by a user",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.addListMember",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "add_list_member",
    description: "Add a member to an X list",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
      userId: z.string().min(1),
    }),
  },
  {
    name: "x.removeListMember",
    provider: "x",
    capability: "write",
    risk_level: "low",
    requires_approval: true,
    output_sensitivity: "low",
    action_type: "remove_list_member",
    description: "Remove a member from an X list",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
      userId: z.string().min(1),
    }),
  },
  {
    name: "x.getListMembers",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_list_members",
    description: "List X list members",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getListTweets",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_list_tweets",
    description: "List posts from an X list timeline",
    redaction_policy: [],
    input_schema: z.object({
      listId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getHomeTimeline",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_home_timeline",
    description: "Get an X user's home timeline",
    redaction_policy: [],
    input_schema: z.object({
      userId: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.searchAllPosts",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "search_all_posts",
    description: "Search X full-archive posts",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
      limit: z.number().int().min(1).max(100).optional(),
    }),
  },
  {
    name: "x.getPostCounts",
    provider: "x",
    capability: "read",
    risk_level: "low",
    requires_approval: false,
    output_sensitivity: "low",
    action_type: "get_post_counts",
    description: "Get count of X posts matching a query",
    redaction_policy: [],
    input_schema: z.object({
      query: z.string().min(1),
    }),
  },
];
