import { createHash } from "node:crypto";
import type { AutomationSandboxProviderMode } from "./index.js";

const PINNED_AGENTS_SDK_PACKAGE = "@openai/agents@0.8.2";
const SANDBOX_RUNNER_DIR = "/sandbox/.keppo-automation-runner";
const VERCEL_RUNNER_DIR = "/vercel/sandbox/.keppo-automation-runner";
const RUNNER_ENTRYPOINT_BASENAME = "keppo-automation-runner.mjs";

export interface SandboxRunnerContract {
  entrypoint_path: string;
  install_packages: string[];
  source_text: string;
}

export const SANDBOX_RUNNER_PACKAGES = [PINNED_AGENTS_SDK_PACKAGE] as const;

const resolveSandboxRunnerDir = (providerMode: AutomationSandboxProviderMode): string => {
  return providerMode === "vercel" ? VERCEL_RUNNER_DIR : SANDBOX_RUNNER_DIR;
};

export const resolveSandboxRunnerEntrypointPath = (
  providerMode: AutomationSandboxProviderMode,
): string => {
  return `${resolveSandboxRunnerDir(providerMode)}/${RUNNER_ENTRYPOINT_BASENAME}`;
};

export const buildAutomationRunTraceId = (automationRunId: string): string => {
  return createHash("sha256").update(automationRunId, "utf8").digest("hex").slice(0, 32);
};

export const buildSandboxRunnerContract = (
  providerMode: AutomationSandboxProviderMode,
): SandboxRunnerContract => {
  return {
    entrypoint_path: resolveSandboxRunnerEntrypointPath(providerMode),
    install_packages: [...SANDBOX_RUNNER_PACKAGES],
    source_text: buildSandboxRunnerSource(),
  };
};

const buildSandboxRunnerSource = (): string => {
  return [
    "import {",
    "  Agent,",
    "  BatchTraceProcessor,",
    "  MCPServerStreamableHttp,",
    "  OpenAIProvider,",
    "  OpenAITracingExporter,",
    "  Runner,",
    "  getGlobalTraceProvider,",
    "  setDefaultOpenAITracingExporter,",
    "  setOpenAIAPI,",
    "  setOpenAIResponsesTransport,",
    "  setTracingExportApiKey,",
    '} from "@openai/agents";',
    "",
    'const RUN_ID = process.env.KEPPO_AUTOMATION_RUN_ID ?? "";',
    'const MODEL = process.env.KEPPO_AUTOMATION_MODEL ?? "";',
    'const INSTRUCTIONS = process.env.KEPPO_AUTOMATION_INSTRUCTIONS ?? "";',
    'const NETWORK_ACCESS = process.env.KEPPO_AUTOMATION_NETWORK_ACCESS ?? "";',
    'const OPENAI_API_KEY = process.env.OPENAI_API_KEY ?? "";',
    'const OPENAI_BASE_URL = process.env.OPENAI_BASE_URL?.trim() ?? "";',
    'const MCP_SERVER_URL = process.env.KEPPO_MCP_SERVER_URL ?? "";',
    'const MCP_BEARER_TOKEN = process.env.KEPPO_MCP_BEARER_TOKEN ?? "";',
    'const MCP_SESSION_ID = process.env.KEPPO_MCP_SESSION_ID?.trim() ?? "";',
    'const LOG_CALLBACK_URL = process.env.KEPPO_LOG_CALLBACK_URL ?? "";',
    'const TRACE_CALLBACK_URL = process.env.KEPPO_TRACE_CALLBACK_URL ?? "";',
    'const TRACE_ID = process.env.KEPPO_OPENAI_TRACE_ID?.trim() ?? "";',
    'const TRACE_GROUP_ID = process.env.KEPPO_OPENAI_TRACE_GROUP_ID?.trim() ?? "";',
    'const TRACE_WORKFLOW_NAME = process.env.KEPPO_OPENAI_TRACE_WORKFLOW_NAME?.trim() ?? "";',
    'const TRACE_METADATA_JSON = process.env.KEPPO_OPENAI_TRACE_METADATA_JSON?.trim() ?? "";',
    'const TRACE_EXPORT_API_KEY = process.env.KEPPO_OPENAI_TRACING_API_KEY?.trim() ?? "";',
    'const TRACE_EXPORT_ENDPOINT = process.env.KEPPO_OPENAI_TRACING_ENDPOINT?.trim() ?? "";',
    'const VERCEL_AUTOMATION_BYPASS_SECRET = process.env.VERCEL_AUTOMATION_BYPASS_SECRET ?? "";',
    "",
    "const truncateText = (value, maxLength = 4000) => {",
    '  if (typeof value !== "string") {',
    '    return "";',
    "  }",
    "  if (value.length <= maxLength) {",
    "    return value;",
    "  }",
    "  return `${value.slice(0, Math.max(0, maxLength - 3))}...`;",
    "};",
    "",
    "const parseJsonMaybe = (value) => {",
    '  if (typeof value !== "string") {',
    "    return undefined;",
    "  }",
    "  const trimmed = value.trim();",
    "  if (trimmed.length === 0) {",
    "    return undefined;",
    "  }",
    '  if (!((trimmed.startsWith("{") && trimmed.endsWith("}")) || (trimmed.startsWith("[") && trimmed.endsWith("]")))) {',
    "    return undefined;",
    "  }",
    "  try {",
    "    return JSON.parse(trimmed);",
    "  } catch {",
    "    return undefined;",
    "  }",
    "};",
    "",
    "const normalizeError = (error) => {",
    '  if (error instanceof Error && typeof error.message === "string" && error.message.trim().length > 0) {',
    "    return error.message.trim();",
    "  }",
    '  if (typeof error === "string" && error.trim().length > 0) {',
    "    return error.trim();",
    "  }",
    "  try {",
    "    return JSON.stringify(error);",
    "  } catch {",
    '    return "Unknown runner error";',
    "  }",
    "};",
    "",
    "const parseTraceMetadata = () => {",
    "  if (!TRACE_METADATA_JSON) {",
    "    return undefined;",
    "  }",
    "  try {",
    "    const parsed = JSON.parse(TRACE_METADATA_JSON);",
    '    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : undefined;',
    "  } catch {",
    "    return undefined;",
    "  }",
    "};",
    "",
    "const extractMessageText = (content) => {",
    "  if (!Array.isArray(content)) {",
    '    return "";',
    "  }",
    "  return content",
    "    .map((part) => {",
    '      if (!part || typeof part !== "object") {',
    '        return "";',
    "      }",
    '      if (part.type === "output_text" && typeof part.text === "string") {',
    "        return part.text;",
    "      }",
    '      if (part.type === "refusal" && typeof part.refusal === "string") {',
    "        return part.refusal;",
    "      }",
    '      if (part.type === "input_text" && typeof part.text === "string") {',
    "        return part.text;",
    "      }",
    '      if (part.type === "reasoning_text" && typeof part.text === "string") {',
    "        return part.text;",
    "      }",
    '      return "";',
    "    })",
    "    .filter((value) => value.length > 0)",
    '    .join("\\n");',
    "};",
    "",
    "const extractReasoningText = (item) => {",
    "  const rawItem = item?.rawItem;",
    "  const rawContent = Array.isArray(rawItem?.rawContent) ? extractMessageText(rawItem.rawContent) : '';",
    "  if (rawContent.length > 0) {",
    "    return rawContent;",
    "  }",
    "  const content = extractMessageText(rawItem?.content);",
    "  return content;",
    "};",
    "",
    "const extractToolArguments = (rawItem) => {",
    "  const parsed = parseJsonMaybe(typeof rawItem?.arguments === 'string' ? rawItem.arguments : '');",
    '  return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : undefined;',
    "};",
    "",
    "const serializeToolOutput = (output) => {",
    '  if (typeof output === "string") {',
    "    return output;",
    "  }",
    "  try {",
    "    return JSON.stringify(output);",
    "  } catch {",
    '    return "";',
    "  }",
    "};",
    "",
    "const postJson = async (url, payload) => {",
    "  if (!url) {",
    "    return;",
    "  }",
    "  const response = await fetch(url, {",
    '    method: "POST",',
    "    headers: {",
    '      "content-type": "application/json",',
    "      ...(VERCEL_AUTOMATION_BYPASS_SECRET",
    '        ? { "x-vercel-protection-bypass": VERCEL_AUTOMATION_BYPASS_SECRET }',
    "        : {}),",
    "    },",
    "    body: JSON.stringify(payload),",
    "  });",
    "  if (!response.ok) {",
    "    const detail = (await response.text()).trim();",
    "    throw new Error(detail || `Callback request failed with status ${String(response.status)}.`);",
    "  }",
    "};",
    "",
    "const postLogLines = async (lines) => {",
    "  if (!LOG_CALLBACK_URL || !RUN_ID || !Array.isArray(lines) || lines.length === 0) {",
    "    return;",
    "  }",
    "  await postJson(LOG_CALLBACK_URL, {",
    "    automation_run_id: RUN_ID,",
    "    lines,",
    "  });",
    "};",
    "",
    "const postTrace = async (payload) => {",
    "  if (!TRACE_CALLBACK_URL || !RUN_ID) {",
    "    return;",
    "  }",
    "  await postJson(TRACE_CALLBACK_URL, {",
    "    automation_run_id: RUN_ID,",
    "    ...payload,",
    "  });",
    "};",
    "",
    "const sendConfigLog = async (key, value) => {",
    "  if (!value) {",
    "    return;",
    "  }",
    "  await postLogLines([",
    "    {",
    '      level: "system",',
    "      content: `${key}: ${value}`,",
    '      event_type: "automation_config",',
    "      event_data: {",
    "        key,",
    "        value,",
    "        source: 'agents_sdk',",
    "      },",
    "    },",
    "  ]);",
    "};",
    "",
    "const mapRunItemEvent = (event) => {",
    "  const item = event?.item;",
    "  const rawItem = item?.rawItem;",
    '  if (!item || typeof item !== "object") {',
    "    return [];",
    "  }",
    "  if (event.name === 'reasoning_item_created') {",
    "    const text = truncateText(extractReasoningText(item));",
    "    return text",
    "      ? [{",
    '          level: "stdout",',
    "          content: text,",
    '          event_type: "thinking",',
    "          event_data: {",
    "            text,",
    "            source: 'agents_sdk',",
    "          },",
    "        }]",
    "      : [];",
    "  }",
    "  if (event.name === 'message_output_created') {",
    "    const text = truncateText(extractMessageText(rawItem?.content));",
    "    const parsed = parseJsonMaybe(text);",
    "    return text",
    "      ? [{",
    '          level: "stdout",',
    "          content: text,",
    '          event_type: "output",',
    "          event_data: {",
    "            text,",
    "            format: parsed === undefined ? 'text' : 'json',",
    "            ...(parsed === undefined ? {} : { parsed }),",
    "            source: 'agents_sdk',",
    "          },",
    "        }]",
    "      : [];",
    "  }",
    "  if (event.name === 'tool_called') {",
    "    const toolName = typeof rawItem?.name === 'string' ? rawItem.name : 'tool';",
    "    const args = extractToolArguments(rawItem);",
    "    return [{",
    '      level: "stdout",',
    '      content: `tool ${toolName}${args ? `(${JSON.stringify(args)})` : ""}`,',
    '      event_type: "tool_call",',
    "      event_data: {",
    "        tool_name: toolName,",
    "        ...(args ? { args } : {}),",
    "        source: 'agents_sdk',",
    "      },",
    "    }];",
    "  }",
    "  if (event.name === 'tool_output') {",
    "    const toolName = typeof rawItem?.name === 'string' ? rawItem.name : 'tool';",
    "    const resultText = truncateText(serializeToolOutput(item.output));",
    "    const parsed = parseJsonMaybe(resultText);",
    "    const status = rawItem?.status === 'completed' ? 'success' : 'error';",
    "    return [{",
    '      level: status === "success" ? "stdout" : "stderr",',
    "      content: resultText || `${toolName} ${status}`,",
    '      event_type: "tool_call",',
    "      event_data: {",
    "        tool_name: toolName,",
    "        status,",
    "        is_result: true,",
    "        ...(resultText ? { result_text: resultText } : {}),",
    "        ...(parsed === undefined ? {} : { result: parsed }),",
    "        source: 'agents_sdk',",
    "      },",
    "    }];",
    "  }",
    "  if (event.name === 'tool_approval_requested') {",
    "    return [{",
    '      level: "system",',
    '      content: "Automation runner requested tool approval.",',
    '      event_type: "system",',
    "      event_data: {",
    '        message: "Automation runner requested tool approval.",',
    "        source: 'agents_sdk',",
    "      },",
    "    }];",
    "  }",
    "  return [];",
    "};",
    "",
    "const validateEnv = () => {",
    "  const missing = [];",
    "  if (!RUN_ID) missing.push('KEPPO_AUTOMATION_RUN_ID');",
    "  if (!MODEL) missing.push('KEPPO_AUTOMATION_MODEL');",
    "  if (!INSTRUCTIONS) missing.push('KEPPO_AUTOMATION_INSTRUCTIONS');",
    "  if (!OPENAI_API_KEY) missing.push('OPENAI_API_KEY');",
    "  if (!MCP_SERVER_URL) missing.push('KEPPO_MCP_SERVER_URL');",
    "  if (!MCP_BEARER_TOKEN) missing.push('KEPPO_MCP_BEARER_TOKEN');",
    "  if (!LOG_CALLBACK_URL) missing.push('KEPPO_LOG_CALLBACK_URL');",
    "  if (missing.length > 0) {",
    '    throw new Error(`Missing required sandbox runner environment: ${missing.join(", ")}`);',
    "  }",
    "};",
    "",
    "const main = async () => {",
    "  validateEnv();",
    "  setOpenAIAPI('responses');",
    "  setOpenAIResponsesTransport('http');",
    "",
    "  const traceMetadata = parseTraceMetadata();",
    "  const tracingEnabled = TRACE_EXPORT_API_KEY.length > 0;",
    "  if (tracingEnabled) {",
    "    if (TRACE_EXPORT_ENDPOINT) {",
    "      getGlobalTraceProvider().setProcessors([",
    "        new BatchTraceProcessor(",
    "          new OpenAITracingExporter({",
    "            apiKey: TRACE_EXPORT_API_KEY,",
    "            endpoint: TRACE_EXPORT_ENDPOINT,",
    "          }),",
    "        ),",
    "      ]);",
    "      getGlobalTraceProvider().startExportLoop();",
    "    } else {",
    "      setTracingExportApiKey(TRACE_EXPORT_API_KEY);",
    "      setDefaultOpenAITracingExporter();",
    "    }",
    "  }",
    "",
    "  await sendConfigLog('model', MODEL);",
    "  await sendConfigLog('provider', OPENAI_BASE_URL ? `openai:${OPENAI_BASE_URL}` : 'openai');",
    "  await sendConfigLog('network access', NETWORK_ACCESS || 'mcp_only');",
    "  await postLogLines([{",
    '    level: "system",',
    "    content: tracingEnabled ? 'OpenAI trace export enabled.' : 'OpenAI trace export disabled.',",
    '    event_type: "system",',
    "    event_data: {",
    "      message: tracingEnabled ? 'OpenAI trace export enabled.' : 'OpenAI trace export disabled.',",
    "      source: 'agents_sdk',",
    "      kind: 'trace_export_status',",
    "      export_status: tracingEnabled ? 'enabled' : 'disabled',",
    "    },",
    "  }]);",
    "",
    "  const modelProvider = new OpenAIProvider({",
    "    apiKey: OPENAI_API_KEY,",
    "    ...(OPENAI_BASE_URL ? { baseURL: OPENAI_BASE_URL } : {}),",
    "    useResponses: true,",
    "    useResponsesWebSocket: false,",
    "  });",
    "",
    "  const mcpServer = new MCPServerStreamableHttp({",
    "    url: MCP_SERVER_URL,",
    "    name: 'keppo',",
    "    ...(MCP_SESSION_ID ? { sessionId: MCP_SESSION_ID } : {}),",
    "    requestInit: {",
    "      headers: {",
    "        authorization: `Bearer ${MCP_BEARER_TOKEN}`,",
    "        ...(VERCEL_AUTOMATION_BYPASS_SECRET",
    '          ? { "x-vercel-protection-bypass": VERCEL_AUTOMATION_BYPASS_SECRET }',
    "          : {}),",
    "      },",
    "    },",
    "  });",
    "",
    "  let result;",
    "  let tracePayload = {",
    "    export_status: tracingEnabled ? 'exported' : 'disabled',",
    "    ...(TRACE_ID ? { trace_id: TRACE_ID } : {}),",
    "    ...(TRACE_GROUP_ID ? { group_id: TRACE_GROUP_ID } : {}),",
    "    ...(TRACE_WORKFLOW_NAME ? { workflow_name: TRACE_WORKFLOW_NAME } : {}),",
    "  };",
    "",
    "  try {",
    "    await mcpServer.connect();",
    "    const agent = new Agent({",
    "      name: 'Keppo Automation Runner',",
    "      instructions: INSTRUCTIONS,",
    "      model: MODEL,",
    "      mcpServers: [mcpServer],",
    "    });",
    "    const runner = new Runner({",
    "      modelProvider,",
    "      tracingDisabled: !tracingEnabled,",
    "      traceIncludeSensitiveData: true,",
    "      ...(TRACE_WORKFLOW_NAME ? { workflowName: TRACE_WORKFLOW_NAME } : {}),",
    "      ...(TRACE_ID ? { traceId: TRACE_ID } : {}),",
    "      ...(TRACE_GROUP_ID ? { groupId: TRACE_GROUP_ID } : {}),",
    "      ...(traceMetadata ? { traceMetadata } : {}),",
    "      ...(tracingEnabled ? { tracing: { apiKey: TRACE_EXPORT_API_KEY } } : {}),",
    "    });",
    "",
    "    const streamed = await runner.run(agent, 'Begin and complete the automation task.', {",
    "      stream: true,",
    "      maxTurns: 64,",
    "    });",
    "",
    "    for await (const event of streamed) {",
    "      if (event?.type === 'run_item_stream_event') {",
    "        const lines = mapRunItemEvent(event);",
    "        if (lines.length > 0) {",
    "          await postLogLines(lines);",
    "        }",
    "      }",
    "    }",
    "",
    "    await streamed.completed;",
    "    if (streamed.error) {",
    "      throw streamed.error;",
    "    }",
    "    result = streamed;",
    "  } catch (error) {",
    "    const message = truncateText(normalizeError(error));",
    "    await postLogLines([{",
    '      level: "stderr",',
    "      content: message,",
    '      event_type: "error",',
    "      event_data: {",
    "        message,",
    "        source: 'agents_sdk',",
    "      },",
    "    }]);",
    "    throw error;",
    "  } finally {",
    "    try {",
    "      if (tracingEnabled) {",
    "        await getGlobalTraceProvider().forceFlush();",
    "        await getGlobalTraceProvider().shutdown();",
    "      }",
    "    } catch (error) {",
    "      tracePayload = {",
    "        ...tracePayload,",
    "        export_status: 'failed',",
    "        error_message: truncateText(normalizeError(error), 1000),",
    "      };",
    "    }",
    "",
    "    if (result?.lastResponseId) {",
    "      tracePayload = {",
    "        ...tracePayload,",
    "        last_response_id: result.lastResponseId,",
    "      };",
    "    }",
    "",
    "    try {",
    "      await postTrace(tracePayload);",
    "    } catch (error) {",
    "      const message = truncateText(normalizeError(error));",
    "      await postLogLines([{",
    '        level: "stderr",',
    "        content: message,",
    '        event_type: "error",',
    "        event_data: {",
    "          message,",
    "          source: 'agents_sdk',",
    "          kind: 'trace_callback_failed',",
    "        },",
    "      }]).catch(() => undefined);",
    "    }",
    "",
    "    await Promise.allSettled([",
    "      mcpServer.close(),",
    "      typeof modelProvider.close === 'function' ? modelProvider.close() : Promise.resolve(),",
    "    ]);",
    "  }",
    "};",
    "",
    "await main();",
  ].join("\n");
};
