#!/usr/bin/env bash
set -euo pipefail

# Usage: commit_and_push.sh "<commit message>"
# Stages all changes, commits with the provided message, and pushes.
# The commit message should be generated by the AI agent, not this script.

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository." >&2
  exit 1
fi

remote_name="origin"
current_branch="$(git rev-parse --abbrev-ref HEAD)"

git add -A
if git diff --cached --quiet; then
  echo "No changes detected after staging; nothing to commit." >&2
  exit 1
fi

if ! git remote get-url "${remote_name}" >/dev/null 2>&1; then
  echo "Remote '${remote_name}' not found." >&2
  exit 1
fi

if [[ $# -lt 1 || -z "$1" ]]; then
  echo "Usage: commit_and_push.sh \"<commit message>\"" >&2
  echo "Error: commit message is required." >&2
  exit 1
fi

message="$1"

git commit -m "${message}"

if [[ "${current_branch}" == "HEAD" ]]; then
  git push "${remote_name}" HEAD
elif git rev-parse --abbrev-ref "${current_branch}@{upstream}" >/dev/null 2>&1; then
  git push
else
  git push -u "${remote_name}" "${current_branch}"
fi

echo "Committed and pushed '${current_branch}' with: ${message}"
