export const REQUEST_PREFIX = "__KEPPO_BRIDGE_REQUEST__";
export const RESULT_PREFIX = "__KEPPO_BRIDGE_RESULT__";

const buildBridgePrelude = (): string[] => {
  return [
    "const logs = [];",
    "const toolCallsExecuted = [];",
    "",
    "const stringifyConsoleArgs = (args) => args.map((value) => {",
    '  if (typeof value === "string") return value;',
    "  try { return JSON.stringify(value); } catch { return String(value); }",
    '}).join(" ");',
    "",
    "const toSafeRecord = (value) => {",
    '  if (value && typeof value === "object" && !Array.isArray(value)) {',
    "    return value;",
    "  }",
    "  return {};",
    "};",
    "",
    "const emitResult = (payload) => {",
    "  process.stdout.write(`${RESULT_PREFIX}${JSON.stringify(payload)}\\n`);",
    "};",
    "",
    "globalThis.console = {",
    "  log: (...args) => logs.push(stringifyConsoleArgs(args)),",
    "  warn: (...args) => logs.push(`[warn] ${stringifyConsoleArgs(args)}`),",
    "  error: (...args) => logs.push(`[error] ${stringifyConsoleArgs(args)}`),",
    "};",
    "",
    "globalThis.__keppo_call_tool = async (toolName, args) => {",
    '  if (typeof toolName !== "string" || toolName.length === 0) {',
    '    throw new Error("Tool name must be a non-empty string.");',
    "  }",
    "  const input = toSafeRecord(args);",
    "  const output = await requestHost({",
    '    kind: "tool",',
    "    toolName,",
    "    input,",
    "  });",
    "  toolCallsExecuted.push({ toolName, input, output });",
    "  return output;",
    "};",
    "",
    "globalThis.__keppo_search_tools = async (query, options) => {",
    '  if (typeof query !== "string" || query.trim().length === 0) {',
    "    return [];",
    "  }",
    "  return requestHost({",
    '    kind: "search",',
    "    query,",
    "    options: toSafeRecord(options),",
    "  });",
    "};",
    "",
    'await import("./sdk.mjs");',
    "",
    "try {",
    "  const returnValue = await (async () => {",
  ];
};

const buildBridgeTail = (): string[] => {
  return [
    "  })();",
    "  emitResult({",
    "    success: true,",
    "    hasReturnValue: returnValue !== undefined,",
    "    returnValue,",
    "    logs,",
    "    toolCallsExecuted,",
    "  });",
    "} catch (error) {",
    "  emitResult({",
    "    success: false,",
    "    error: error instanceof Error ? error.message : String(error),",
    "    logs,",
    "    toolCallsExecuted,",
    "  });",
    "  process.exitCode = 1;",
    "}",
  ];
};

export const buildBridgeEntrySource = (code: string, responseDir: string): string => {
  return [
    'import { mkdir, readFile, rm } from "node:fs/promises";',
    'import { setTimeout as sleep } from "node:timers/promises";',
    "",
    `const REQUEST_PREFIX = ${JSON.stringify(REQUEST_PREFIX)};`,
    `const RESULT_PREFIX = ${JSON.stringify(RESULT_PREFIX)};`,
    `const RESPONSE_DIR = ${JSON.stringify(responseDir)};`,
    "const REQUEST_TIMEOUT_MS = 15_000;",
    "",
    "const requestHost = async (payload) => {",
    "  const requestId = `${Date.now()}_${Math.random().toString(16).slice(2, 10)}`;",
    "  const responsePath = `${RESPONSE_DIR}/${requestId}.json`;",
    "  process.stdout.write(",
    "    `${REQUEST_PREFIX}${JSON.stringify({ requestId, responsePath, ...payload })}\\n`,",
    "  );",
    "",
    "  const started = Date.now();",
    "  while (Date.now() - started < REQUEST_TIMEOUT_MS) {",
    "    try {",
    '      const raw = await readFile(responsePath, "utf8");',
    "      await rm(responsePath, { force: true });",
    "      const response = JSON.parse(raw);",
    "      if (response?.ok) {",
    "        return response.value;",
    "      }",
    "      throw new Error(",
    '        typeof response?.error === "string" ? response.error : "Bridge request failed.",',
    "      );",
    "    } catch (error) {",
    '      const code = error && typeof error === "object" ? error.code : undefined;',
    '      if (code === "ENOENT") {',
    "        await sleep(15);",
    "        continue;",
    "      }",
    "      if (error instanceof SyntaxError) {",
    "        await sleep(15);",
    "        continue;",
    "      }",
    "      throw error;",
    "    }",
    "  }",
    '  throw new Error("Bridge response timed out.");',
    "};",
    "",
    "await mkdir(RESPONSE_DIR, { recursive: true });",
    ...buildBridgePrelude(),
    code,
    ...buildBridgeTail(),
  ].join("\n");
};

export const buildHttpBridgeEntrySource = (code: string, bridgeCallbackUrl: string): string => {
  return [
    `const REQUEST_PREFIX = ${JSON.stringify(REQUEST_PREFIX)};`,
    `const RESULT_PREFIX = ${JSON.stringify(RESULT_PREFIX)};`,
    `const BRIDGE_CALLBACK_URL = ${JSON.stringify(bridgeCallbackUrl)};`,
    'const BRIDGE_AUTH_TOKEN = process.env["KEPPO_BRIDGE_AUTH_TOKEN"] ?? "";',
    "",
    "const requestHost = async (payload) => {",
    "  const requestId = `${Date.now()}_${Math.random().toString(16).slice(2, 10)}`;",
    "  const requestPayload = { requestId, ...payload };",
    "  process.stdout.write(`${REQUEST_PREFIX}${JSON.stringify(requestPayload)}\\n`);",
    "",
    "  const response = await fetch(BRIDGE_CALLBACK_URL, {",
    '    method: "POST",',
    "    headers: {",
    '      "content-type": "application/json",',
    '      ...(BRIDGE_AUTH_TOKEN ? { authorization: `Bearer ${BRIDGE_AUTH_TOKEN}` } : {}),',
    "    },",
    "    body: JSON.stringify(requestPayload),",
    "  });",
    "  const raw = await response.text();",
    "  let parsed;",
    "  try {",
    "    parsed = JSON.parse(raw);",
    "  } catch {",
    '    throw new Error("Bridge response was not valid JSON.");',
    "  }",
    "  if (!response.ok || !parsed?.ok) {",
    "    throw new Error(",
    '      typeof parsed?.error === "string" ? parsed.error : "Bridge request failed.",',
    "    );",
    "  }",
    "  return parsed.value;",
    "};",
    "",
    ...buildBridgePrelude(),
    code,
    ...buildBridgeTail(),
  ].join("\n");
};
