#!/usr/bin/env bash
set -euo pipefail

# Usage: commit.sh "<commit message>"
# Stages all changes and commits with the provided message.
# The commit message should be generated by the AI agent, not this script.

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not a git repository." >&2
  exit 1
fi

git add -A
if git diff --cached --quiet; then
  echo "No changes detected after staging; nothing to commit." >&2
  exit 1
fi

if [[ $# -lt 1 || -z "$1" ]]; then
  echo "Usage: commit.sh \"<commit message>\"" >&2
  echo "Error: commit message is required." >&2
  exit 1
fi

message="$1"

git commit -m "${message}"

echo "Committed with: ${message}"
