import type { PlannedActionCatalogSeed } from "./types.js";

export const githubPlannedActionCatalogSeeds: ReadonlyArray<PlannedActionCatalogSeed> = [
  {
    providerId: "github",
    toolName: "github.createReview",
    actionType: "createReview",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/pulls/{n}/reviews",
    description: "Submit PR review (APPROVE/REQUEST_CHANGES/COMMENT)",
  },
  {
    providerId: "github",
    toolName: "github.listReviews",
    actionType: "listReviews",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/pulls/{n}/reviews",
    description: "List reviews on a PR",
  },
  {
    providerId: "github",
    toolName: "github.dismissReview",
    actionType: "dismissReview",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "PUT /repos/{owner}/{repo}/pulls/{n}/reviews/{id}/dismissals",
    description: "Dismiss a review",
  },
  {
    providerId: "github",
    toolName: "github.requestReviewers",
    actionType: "requestReviewers",
    capability: "write",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/pulls/{n}/requested_reviewers",
    description: "Request specific reviewers",
  },
  {
    providerId: "github",
    toolName: "github.removeReviewers",
    actionType: "removeReviewers",
    capability: "write",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "DELETE /repos/{owner}/{repo}/pulls/{n}/requested_reviewers",
    description: "Remove review requests",
  },
  {
    providerId: "github",
    toolName: "github.createReviewComment",
    actionType: "createReviewComment",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/pulls/{n}/comments",
    description: "Comment on specific diff lines",
  },
  {
    providerId: "github",
    toolName: "github.listCommits",
    actionType: "listCommits",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/commits",
    description: "List commits in a repo",
  },
  {
    providerId: "github",
    toolName: "github.compareCommits",
    actionType: "compareCommits",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/compare/{basehead}",
    description: "Compare two refs (diff)",
  },
  {
    providerId: "github",
    toolName: "github.getCommitStatus",
    actionType: "getCommitStatus",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/commits/{ref}/status",
    description: "Get combined CI status for a ref",
  },
  {
    providerId: "github",
    toolName: "github.listCheckRuns",
    actionType: "listCheckRuns",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/commits/{ref}/check-runs",
    description: "List check runs for a commit/PR",
  },
  {
    providerId: "github",
    toolName: "github.listWorkflowRuns",
    actionType: "listWorkflowRuns",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/actions/runs",
    description: "List workflow runs",
  },
  {
    providerId: "github",
    toolName: "github.getWorkflowRun",
    actionType: "getWorkflowRun",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/actions/runs/{id}",
    description: "Get workflow run details",
  },
  {
    providerId: "github",
    toolName: "github.triggerWorkflow",
    actionType: "triggerWorkflow",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/actions/workflows/{id}/dispatches",
    description: "Dispatch a workflow run",
  },
  {
    providerId: "github",
    toolName: "github.cancelWorkflowRun",
    actionType: "cancelWorkflowRun",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/actions/runs/{id}/cancel",
    description: "Cancel a running workflow",
  },
  {
    providerId: "github",
    toolName: "github.rerunWorkflow",
    actionType: "rerunWorkflow",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "POST /repos/{owner}/{repo}/actions/runs/{id}/rerun",
    description: "Re-run a failed workflow",
  },
  {
    providerId: "github",
    toolName: "github.updatePullRequest",
    actionType: "updatePullRequest",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "PATCH /repos/{owner}/{repo}/pulls/{n}",
    description: "Update PR title, body, state, base",
  },
  {
    providerId: "github",
    toolName: "github.listPRCommits",
    actionType: "listPRCommits",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/pulls/{n}/commits",
    description: "List commits on a PR",
  },
  {
    providerId: "github",
    toolName: "github.listIssueComments",
    actionType: "listIssueComments",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "GET /repos/{owner}/{repo}/issues/{n}/comments",
    description: "List comments on an issue",
  },
  {
    providerId: "github",
    toolName: "github.updateComment",
    actionType: "updateComment",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "PATCH /repos/{owner}/{repo}/issues/comments/{id}",
    description: "Update an issue comment",
  },
  {
    providerId: "github",
    toolName: "github.deleteComment",
    actionType: "deleteComment",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "DELETE /repos/{owner}/{repo}/issues/comments/{id}",
    description: "Delete an issue comment",
  },
  {
    providerId: "github",
    toolName: "github.lockIssue",
    actionType: "lockIssue",
    capability: "write",
    riskLevel: "medium",
    tier: "T3",
    sdkMethod: "PUT /repos/{owner}/{repo}/issues/{n}/lock",
    description: "Lock an issue conversation",
  },
  {
    providerId: "github",
    toolName: "github.unlockIssue",
    actionType: "unlockIssue",
    capability: "write",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "DELETE /repos/{owner}/{repo}/issues/{n}/lock",
    description: "Unlock an issue conversation",
  },
  {
    providerId: "github",
    toolName: "github.listIssueEvents",
    actionType: "listIssueEvents",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /repos/{owner}/{repo}/issues/{n}/events",
    description: "List events for an issue",
  },
  {
    providerId: "github",
    toolName: "github.listIssueTimeline",
    actionType: "listIssueTimeline",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /repos/{owner}/{repo}/issues/{n}/timeline",
    description: "List timeline events",
  },
  {
    providerId: "github",
    toolName: "github.searchCode",
    actionType: "searchCode",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /search/code",
    description: "Search code across repos",
  },
  {
    providerId: "github",
    toolName: "github.searchRepositories",
    actionType: "searchRepositories",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /search/repositories",
    description: "Search repositories",
  },
  {
    providerId: "github",
    toolName: "github.listNotifications",
    actionType: "listNotifications",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /notifications",
    description: "List notifications for user",
  },
  {
    providerId: "github",
    toolName: "github.markNotificationsRead",
    actionType: "markNotificationsRead",
    capability: "write",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "PUT /notifications",
    description: "Mark all notifications as read",
  },
  {
    providerId: "github",
    toolName: "github.rerunFailedJobs",
    actionType: "rerunFailedJobs",
    capability: "write",
    riskLevel: "medium",
    tier: "T3",
    sdkMethod: "POST /repos/{owner}/{repo}/actions/runs/{id}/rerun-failed-jobs",
    description: "Re-run only failed jobs",
  },
  {
    providerId: "github",
    toolName: "github.getWorkflowJobLogs",
    actionType: "getWorkflowJobLogs",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /repos/{owner}/{repo}/actions/jobs/{id}/logs",
    description: "Download job logs",
  },
  {
    providerId: "github",
    toolName: "github.updatePRBranch",
    actionType: "updatePRBranch",
    capability: "write",
    riskLevel: "medium",
    tier: "T3",
    sdkMethod: "POST /repos/{owner}/{repo}/pulls/{n}/update-branch",
    description: "Update PR branch with base",
  },
  {
    providerId: "github",
    toolName: "github.createReaction",
    actionType: "createReaction",
    capability: "write",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "POST /repos/{owner}/{repo}/issues/{n}/reactions",
    description: "Add reaction to issue",
  },
  {
    providerId: "github",
    toolName: "github.deleteReaction",
    actionType: "deleteReaction",
    capability: "write",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "DELETE /repos/{owner}/{repo}/issues/{n}/reactions/{id}",
    description: "Remove reaction",
  },
  {
    providerId: "github",
    toolName: "github.listOrgRepos",
    actionType: "listOrgRepos",
    capability: "read",
    riskLevel: "low",
    tier: "T3",
    sdkMethod: "GET /orgs/{org}/repos",
    description: "List org repositories",
  },
  {
    providerId: "github",
    toolName: "github.createDispatchEvent",
    actionType: "createDispatchEvent",
    capability: "write",
    riskLevel: "medium",
    tier: "T3",
    sdkMethod: "POST /repos/{owner}/{repo}/dispatches",
    description: "Create repository dispatch event",
  },
] as const;
