import type { PlannedActionCatalogSeed } from "./types.js";

export const notionPlannedActionCatalogSeeds: ReadonlyArray<PlannedActionCatalogSeed> = [
  {
    providerId: "notion",
    toolName: "notion.getPage",
    actionType: "getPage",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "GET /v1/pages/{id}",
    description: "Get page properties and metadata",
  },
  {
    providerId: "notion",
    toolName: "notion.updatePage",
    actionType: "updatePage",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "PATCH /v1/pages/{id}",
    description: "Update page properties (title, status, etc.)",
  },
  {
    providerId: "notion",
    toolName: "notion.queryDatabase",
    actionType: "queryDatabase",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "POST /v1/databases/{id}/query",
    description: "Filter and sort database entries",
  },
  {
    providerId: "notion",
    toolName: "notion.getDatabase",
    actionType: "getDatabase",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "GET /v1/databases/{id}",
    description: "Get database schema/properties",
  },
  {
    providerId: "notion",
    toolName: "notion.getBlockChildren",
    actionType: "getBlockChildren",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "GET /v1/blocks/{id}/children",
    description: "Read page content (blocks)",
  },
  {
    providerId: "notion",
    toolName: "notion.appendBlockChildren",
    actionType: "appendBlockChildren",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "PATCH /v1/blocks/{id}/children",
    description: "Append content to a page",
  },
] as const;
