import type { PlannedActionCatalogSeed } from "./types.js";

export const stripePlannedActionCatalogSeeds: ReadonlyArray<PlannedActionCatalogSeed> = [
  {
    providerId: "stripe",
    toolName: "stripe.searchCustomers",
    actionType: "searchCustomers",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "customers.search",
    description: "Find customer by email/name when ID unknown",
  },
  {
    providerId: "stripe",
    toolName: "stripe.updateCustomer",
    actionType: "updateCustomer",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "customers.update",
    description: "Change email, name, address, metadata",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getSubscription",
    actionType: "getSubscription",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "subscriptions.retrieve",
    description: "Get full subscription details",
  },
  {
    providerId: "stripe",
    toolName: "stripe.updateSubscription",
    actionType: "updateSubscription",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "subscriptions.update",
    description: "Change plan, quantity, trial, apply coupon, prorate",
  },
  {
    providerId: "stripe",
    toolName: "stripe.resumeSubscription",
    actionType: "resumeSubscription",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "subscriptions.resume",
    description: "Unpause a paused subscription",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getInvoice",
    actionType: "getInvoice",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "invoices.retrieve",
    description: "Pull up a specific invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.previewInvoice",
    actionType: "previewInvoice",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "invoices.createPreview",
    description: "Show customer their upcoming bill",
  },
  {
    providerId: "stripe",
    toolName: "stripe.sendInvoice",
    actionType: "sendInvoice",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "invoices.sendInvoice",
    description: "Resend invoice email",
  },
  {
    providerId: "stripe",
    toolName: "stripe.voidInvoice",
    actionType: "voidInvoice",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "invoices.voidInvoice",
    description: "Void an incorrect invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.payInvoice",
    actionType: "payInvoice",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "invoices.pay",
    description: "Retry payment on an open invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listPaymentMethods",
    actionType: "listPaymentMethods",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "paymentMethods.list",
    description: "See cards/bank accounts on file",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getRefund",
    actionType: "getRefund",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "refunds.retrieve",
    description: "Check refund status",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listRefunds",
    actionType: "listRefunds",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "refunds.list",
    description: "View refund history",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getCharge",
    actionType: "getCharge",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "charges.retrieve",
    description: "Look up specific charge details",
  },
  {
    providerId: "stripe",
    toolName: "stripe.createCreditNote",
    actionType: "createCreditNote",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "creditNotes.create",
    description: "Issue partial credit against an invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listCreditNotes",
    actionType: "listCreditNotes",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "creditNotes.list",
    description: "View credit note history",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getDispute",
    actionType: "getDispute",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "disputes.retrieve",
    description: "View dispute details and deadline",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listDisputes",
    actionType: "listDisputes",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "disputes.list",
    description: "View all open disputes",
  },
  {
    providerId: "stripe",
    toolName: "stripe.updateDispute",
    actionType: "updateDispute",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "disputes.update",
    description: "Submit evidence for a dispute",
  },
  {
    providerId: "stripe",
    toolName: "stripe.closeDispute",
    actionType: "closeDispute",
    capability: "write",
    riskLevel: "high",
    tier: "T1",
    sdkMethod: "disputes.close",
    description: "Accept a dispute",
  },
  {
    providerId: "stripe",
    toolName: "stripe.createPortalSession",
    actionType: "createPortalSession",
    capability: "write",
    riskLevel: "medium",
    tier: "T1",
    sdkMethod: "billingPortal.sessions.create",
    description: "Generate self-service portal link",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listBalanceTransactions",
    actionType: "listBalanceTransactions",
    capability: "read",
    riskLevel: "low",
    tier: "T1",
    sdkMethod: "customerBalanceTransactions.list",
    description: "View history of balance adjustments",
  },
  {
    providerId: "stripe",
    toolName: "stripe.searchCharges",
    actionType: "searchCharges",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "charges.search",
    description: "Find charges by email, metadata",
  },
  {
    providerId: "stripe",
    toolName: "stripe.searchSubscriptions",
    actionType: "searchSubscriptions",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "subscriptions.search",
    description: "Find subscriptions by status, metadata",
  },
  {
    providerId: "stripe",
    toolName: "stripe.searchInvoices",
    actionType: "searchInvoices",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "invoices.search",
    description: "Find invoices by customer, status",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getPaymentIntent",
    actionType: "getPaymentIntent",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "paymentIntents.retrieve",
    description: "Payment detail lookup, decline reasons",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listPaymentIntents",
    actionType: "listPaymentIntents",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "paymentIntents.list",
    description: "View payment attempts",
  },
  {
    providerId: "stripe",
    toolName: "stripe.searchPaymentIntents",
    actionType: "searchPaymentIntents",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "paymentIntents.search",
    description: "Find failed payments",
  },
  {
    providerId: "stripe",
    toolName: "stripe.detachPaymentMethod",
    actionType: "detachPaymentMethod",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "paymentMethods.detach",
    description: "Remove old/expired card",
  },
  {
    providerId: "stripe",
    toolName: "stripe.cancelRefund",
    actionType: "cancelRefund",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "refunds.cancel",
    description: "Cancel a pending refund",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getCoupon",
    actionType: "getCoupon",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "coupons.retrieve",
    description: "Verify coupon terms",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listCoupons",
    actionType: "listCoupons",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "coupons.list",
    description: "View available coupons",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getPromotionCode",
    actionType: "getPromotionCode",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "promotionCodes.retrieve",
    description: "Verify promo code validity",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listPromotionCodes",
    actionType: "listPromotionCodes",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "promotionCodes.list",
    description: "View available promo codes",
  },
  {
    providerId: "stripe",
    toolName: "stripe.createInvoiceItem",
    actionType: "createInvoiceItem",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "invoiceItems.create",
    description: "Add one-off charge/credit to next invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.deleteInvoiceItem",
    actionType: "deleteInvoiceItem",
    capability: "write",
    riskLevel: "medium",
    tier: "T2",
    sdkMethod: "invoiceItems.delete",
    description: "Remove erroneous pending charge",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getProduct",
    actionType: "getProduct",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "products.retrieve",
    description: "Look up product details",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listProducts",
    actionType: "listProducts",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "products.list",
    description: "See available products",
  },
  {
    providerId: "stripe",
    toolName: "stripe.getPrice",
    actionType: "getPrice",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "prices.retrieve",
    description: "Look up pricing details",
  },
  {
    providerId: "stripe",
    toolName: "stripe.listPrices",
    actionType: "listPrices",
    capability: "read",
    riskLevel: "low",
    tier: "T2",
    sdkMethod: "prices.list",
    description: "See available pricing",
  },
  {
    providerId: "stripe",
    toolName: "stripe.finalizeInvoice",
    actionType: "finalizeInvoice",
    capability: "write",
    riskLevel: "high",
    tier: "T2",
    sdkMethod: "invoices.finalizeInvoice",
    description: "Finalize a draft invoice",
  },
  {
    providerId: "stripe",
    toolName: "stripe.markUncollectible",
    actionType: "markUncollectible",
    capability: "write",
    riskLevel: "high",
    tier: "T2",
    sdkMethod: "invoices.markUncollectible",
    description: "Write off a bad debt",
  },
] as const;
